### ISSUE TITLE
java.lang.NullPointerException at ca.mcgill.mcb.pcingola.interval.Transcript.cds(Transcript.java:503)

### ISSUE THREAD

**Issue by summerela** [pcingola/SnpEff#114]
I'm running into this error frequently with SnpEff version SnpEff 4.1l (build 2015-10-03).

    Error: Error while processing VCF entry (line 10361872) :
	13	32893291	rs80358435	G	T	.	.	.
    java.lang.NullPointerException
	at ca.mcgill.mcb.pcingola.interval.Transcript.cds(Transcript.java:503)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.getCdsLength(VariantEffect.java:329)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.set(VcfEffect.java:1043)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:145)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:97)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
	at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:66)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:18)
	at ca.mcgill.mcb.pcingola.akka.Worker.calculate(Worker.java:51)
	at ca.mcgill.mcb.pcingola.akka.Worker.onReceive(Worker.java:62)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:154)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:153)
	at akka.actor.Actor$class.apply(Actor.scala:311)
	at akka.actor.UntypedActor.apply(UntypedActor.scala:93)
	at akka.actor.ActorCell.invoke(ActorCell.scala:619)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:196)
	at akka.dispatch.Mailbox.run(Mailbox.scala:178)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by pcingola** [comment]
Could you send a sample VCF and the full command line you are using?
I'll check the issue and get back to you.

**Comment by pcingola** [comment]
Guidelines here: http://snpeff.sourceforge.net/about.html#bugs
With that info I can reproduce the error condition and analyze the issue.
Thank you.

**Comment by summerela** [comment]
Here's a sample of the vcf file in txt format. 
[sample.txt](https://github.com/pcingola/SnpEff/files/47940/sample.txt)

This is the command I used; 

     /tools/java/jdk1.7/bin/java -Xmx32g -jar /users/selasady/tools/snpEff/snpEff.jar -t -v -noStats GRCh37.74 all_vars.txt > allvars_snpeff.vcf

**Comment by pcingola** [comment]
What you sent is not a valid VCF file. Could you please send 
a proper VCF sample file so I can use it for the command line?

**Comment by pcingola** [comment]
Converted the TXT file to VCF, run the program and everything runs OK.
Sorry, but I cannot replicate the error condition with the data you sent...

**Comment by summerela** [comment]
Github does not allow upload of VCF format, so I changed the file extension
to .txt. However, the VCF format is a tab-delimited format with a header,
so it's the exact same format as what I sent you, but with a header. Does
snpeff require the vcf header, is that what you're saying? Does it require
column names? Dots for the gt field? etc?

Thanks,
Summer

On Tue, Dec 1, 2015 at 8:13 AM, Pablo Cingolani <notifications@github.com>
wrote:

> Converted the TXT file to VCF, run the program and everything runs OK.
> Sorry, but I cannot replicate the error condition with the data you sent...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcingola/SnpEff/issues/114#issuecomment-161016521>.
>



-- 
Thanks,
Summer Rae
summerrae78@gmail.com

**Comment by pcingola** [comment]
Hi,
   It is not a simple "change of extension" issue, the file is not a valid VCF.
Anyway, I converted it to VCF and even then I could not replicate the error 
condition when I tried your command line. 
  Just to be clear, I'm not nitpicking about VCF format (I don't really care about 
that) I just want to replicate the issue you have so I can debug it. Unfortunately, I've 
been unable to replicate the error condition with your data & command line.
  I'll be releasing version 4.2 soon, may be you can try that version and contact 
me if the problem persists. Does it sound reasonable?

**Comment by summerela** [comment]
Hi Pablo-

Thanks for the quick reply. I didn't mean to imply that you are nitpicking
at all, I would just like to know what the exact requirements are so that I
can use snpeff without issue. Would you mind telling me what you did to
convert it properly? I'm currently just using a quick script I wrote in
python and then validating the results with vcftools.

Thanks again,
Summer

On Tue, Dec 1, 2015 at 8:47 AM, Pablo Cingolani <notifications@github.com>
wrote:

> Hi,
> It is not a simple "change of extension" issue, the file is not a valid
> VCF.
> Anyway, I converted it to VCF and even then I could not replicate the
> error
> condition when I tried your command line.
> Just to be clear, I'm not nitpicking about VCF format (I don't really care
> about
> that) I just want to replicate the issue you have so I can debug it.
> Unfortunately, I've
> been unable to replicate the error condition with your data & command line.
> I'll be releasing version 4.2 soon, may be you can try that version and
> contact
> me if the problem persists. Does it sound reasonable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcingola/SnpEff/issues/114#issuecomment-161027671>.
>



-- 
Thanks,
Summer Rae
summerrae78@gmail.com

**Comment by pcingola** [comment]
For this case I just run the vcfBareBones.pl script (available in SnpEff's 'scripts' dir).
VCF requires 8 columns (at least up to the INFO one) even if they are empty ('.'). 
Also, newer VCF versions require entries to be sorted (SnpEfff doesn't 
complain, but other software downstream might). Headers are highly 
recommended (again SnpEff doesn't complain much about this, but other 
software downstream might simply crash).

**Comment by summerela** [comment]
Thanks so much! I'll try all of that, and if I get any more informative
information I will let you know.

On Tue, Dec 1, 2015 at 9:02 AM, Pablo Cingolani <notifications@github.com>
wrote:

> For this case I just run the vcfBareBones.pl script (available in SnpEff's
> 'scripts' dir).
> VCF requires 8 columns (at least up to the INFO one) even if they are
> empty ('.').
> Also, newer VCF versions require entries to be sorted (SnpEfff doesn't
> complain, but other software downstream might). Headers are highly
> recommended (again SnpEff doesn't complain much about this, but other
> software downstream might simply crash).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcingola/SnpEff/issues/114#issuecomment-161032530>.
>



-- 
Thanks,
Summer Rae
summerrae78@gmail.com

**Comment by summerela** [comment]
I've run all my VCF files through vcfBareBones.pl and snpeff is still hanging on the followiing error: 

    Error: Error while processing VCF entry (line 1923230) :
	5	7870888	.	C	T	.	.	.
    java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at ca.mcgill.mcb.pcingola.interval.Transcript.get5primeUtrs(Transcript.java:1039)
	at ca.mcgill.mcb.pcingola.interval.Transcript.cds(Transcript.java:502)
	at ca.mcgill.mcb.pcingola.interval.Transcript.protein(Transcript.java:1394)
	at ca.mcgill.mcb.pcingola.interval.Transcript.isErrorStopCodonsInCds(Transcript.java:1267)
	at ca.mcgill.mcb.pcingola.interval.Transcript.sanityCheck(Transcript.java:1495)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.setMarker(VariantEffect.java:746)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.set(VariantEffect.java:670)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffects.add(VariantEffects.java:34)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffects.add(VariantEffects.java:42)
	at ca.mcgill.mcb.pcingola.interval.Utr5prime.variantEffect(Utr5prime.java:140)
	at ca.mcgill.mcb.pcingola.interval.Transcript.variantEffect(Transcript.java:1853)
	at ca.mcgill.mcb.pcingola.interval.Gene.variantEffect(Gene.java:522)
	at ca.mcgill.mcb.pcingola.snpEffect.SnpEffectPredictor.variantEffect(SnpEffectPredictor.java:677)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:51)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:18)
	at ca.mcgill.mcb.pcingola.akka.Worker.calculate(Worker.java:51)
	at ca.mcgill.mcb.pcingola.akka.Worker.onReceive(Worker.java:62)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:154)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:153)
	at akka.actor.Actor$class.apply(Actor.scala:311)
	at akka.actor.UntypedActor.apply(UntypedActor.scala:93)
	at akka.actor.ActorCell.invoke(ActorCell.scala:619)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:196)
	at akka.dispatch.Mailbox.run(Mailbox.scala:178)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec
       (AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

Looks like a similar issue reported here: 
http://examples.javacodegeeks.com/java-basics/exceptions/java-util-concurrentmodificationexception-how-to-handle-concurrent-modification-exception/

**Comment by pcingola** [comment]
Hi, this looks like a different problem than the one stated in the title of the issue.
Please open a separate bug report and remember to send enough info to replicate the bug condition (guidelines here http://snpeff.sourceforge.net/about.html#bugs)

Also, The link you sent is a generic link not related to SnpEff.
