### ISSUE TITLE
java.lang.NullPointerException at ca.mcgill.mcb.pcingola.interval.codonChange.CodonChange.codonChange(CodonChange.java:156)

### ISSUE THREAD

**Issue by summerela** [pcingola/SnpEff#116]
Hi-

I'm running into this error while running SnpEff version SnpEff 4.1l (build 2015-10-03).

    java.lang.NullPointerException
	at ca.mcgill.mcb.pcingola.interval.codonChange.CodonChange.codonChange(CodonChange.java:156)
	at ca.mcgill.mcb.pcingola.interval.Exon.variantEffect(Exon.java:337)
	at ca.mcgill.mcb.pcingola.interval.Transcript.variantEffect(Transcript.java:1808)
	at ca.mcgill.mcb.pcingola.interval.Gene.variantEffect(Gene.java:504)
	at ca.mcgill.mcb.pcingola.snpEffect.SnpEffectPredictor.variantEffect(SnpEffectPredictor.java:644)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:51)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:18)
	at ca.mcgill.mcb.pcingola.akka.Worker.calculate(Worker.java:51)
	at ca.mcgill.mcb.pcingola.akka.Worker.onReceive(Worker.java:62)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:154)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:153)
	at akka.actor.Actor$class.apply(Actor.scala:311)
	at akka.actor.UntypedActor.apply(UntypedActor.scala:93)
	at akka.actor.ActorCell.invoke(ActorCell.scala:619)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:196)
	at akka.dispatch.Mailbox.run(Mailbox.scala:178)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by pcingola** [comment]
Closing this one. You seem to be opening similar/ same issues

**Comment by summerela** [comment]
Oh sorry, they're all different errors, so I normally get yelled at for putting multiple errors in one report :) Sending you a sample vcf.

**Comment by pcingola** [comment]
Please follow the guidelines so I can reproduce your error condition:

   http://snpeff.sourceforge.net/about.html#bugs

You can send a sample VCF having all problems you reported (likely to be 
the same issue but I can double check).
