### ISSUE TITLE
java.lang.NullPointerException at java.util.Collections.sort(Collections.java:216) 	at ca.mcgill.mcb.pcingola.interval.IntervalAndSubIntervals.sortedStrand(IntervalAndSubIntervals.java:258)

### ISSUE THREAD

**Issue by summerela** [pcingola/SnpEff#117]
Hi-

I'm running into this error while running SnpEff version SnpEff 4.1l (build 2015-10-03).

    Error: Error while processing VCF entry (line 9060089) :
	20	60456738	rs78694756	G	C	.	.	.
     java.lang.NullPointerException
	at java.util.Collections.sort(Collections.java:216)
	at ca.mcgill.mcb.pcingola.interval.IntervalAndSubIntervals.sortedStrand(IntervalAndSubIntervals.java:258)
	at ca.mcgill.mcb.pcingola.interval.Transcript.cds(Transcript.java:493)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.getCdsLength(VariantEffect.java:329)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.set(VcfEffect.java:1043)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:145)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:97)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
	at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:66)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:18)
	at ca.mcgill.mcb.pcingola.akka.Worker.calculate(Worker.java:51)
	at ca.mcgill.mcb.pcingola.akka.Worker.onReceive(Worker.java:62)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:154)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:153)
	at akka.actor.Actor$class.apply(Actor.scala:311)
	at akka.actor.UntypedActor.apply(UntypedActor.scala:93)
	at akka.actor.ActorCell.invoke(ActorCell.scala:619)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:196)
	at akka.dispatch.Mailbox.run(Mailbox.scala:178)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by pcingola** [comment]
Please make sure you follow the guidelines for reporting bugs:
   http://snpeff.sourceforge.net/about.html#bugs

**Comment by pcingola** [comment]
Closing: Seems like the same issue you've already opened twice.
