### ISSUE TITLE
HGVS interval error on structural variants near the ends of chromosomes

### ISSUE THREAD

**Issue by chapmanb** [pcingola/SnpEff#128]
Pablo;
We're running into an issue with snpEff 4.2 on structural variants. This was initially reported by @bwubb in https://github.com/chapmanb/bcbio-nextgen/issues/1205 and here's a small reproducible test case:

https://s3.amazonaws.com/chapmanb/testcases/snpeff_manta_hgvs.tar.gz

Adding `-noHgvs` fixes the issue as a temporary workaround. Thanks so much, please let me know if I can provide anything else to help with debugging.

```
Error: Error while processing VCF entry (line 123) :
	GL000241.1	1	MantaBND:194083:0:1:0:5:0:0	G	]GL000219.1:59505]G	.	MaxDepth	SVTYPE=BND;MATEID=MantaBND:194083:0:1:0:5:0:1;CIPOS=0,10;HOMLEN=10;HOMSEQ=ATCTGAAGAC;BND_DEPTH=101;MATE_BND_DEPTH=247;AC=0;AN=0	PR:SR	0,0:0,0
java.lang.RuntimeException: Interval error: end before start.
	Class        : Marker
	Start        : 0
	End          : -1
	ID           : 
	Parent class : Chromosome
	Parent       : GL000241.1	0-42151 CHROMOSOME 'GL000241.1'
java.lang.RuntimeException: Interval error: end before start.
	Class        : Marker
	Start        : 0
	End          : -1
	ID           : 
	Parent class : Chromosome
	Parent       : GL000241.1	0-42151 CHROMOSOME 'GL000241.1'
	at ca.mcgill.mcb.pcingola.interval.Interval.<init>(Interval.java:38)
	at ca.mcgill.mcb.pcingola.interval.Marker.<init>(Marker.java:37)
	at ca.mcgill.mcb.pcingola.snpEffect.HgvsDna.isDuplication(HgvsDna.java:117)
	at ca.mcgill.mcb.pcingola.snpEffect.HgvsDna.toString(HgvsDna.java:394)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.getHgvsDna(VariantEffect.java:544)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.set(VcfEffect.java:1043)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:147)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:97)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
	at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
	at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.printSection(OutputFormatter.java:145)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:278)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:446)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:138)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:978)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:136)
```

**Comment by pcingola** [comment]
Fixed in development version. 
I'll try to release version 4.3 soon.

**Comment by chapmanb** [comment]
Pablo -- brilliant, thank you. Looking forward to testing this when 4.3 comes out. Thanks again for all the work on snpEff.
