### ISSUE TITLE
java.lang.RuntimeException: Interval error: end before start.

### ISSUE THREAD

**Issue by amphun** [pcingola/SnpEff#134]
Dear All,

I'm new to SnpEff. Here is the error while I try to run SnpEff.
Any suggestions please?

java.lang.RuntimeException: Interval error: end before start.
    Class        : Marker
    Start        : 19948
    End          : 19161
    ID           : 
    Parent class : Chromosome
    Parent       : 1    0-8033584 CHROMOSOME '1'
    at ca.mcgill.mcb.pcingola.interval.Interval.<init>(Interval.java:38)
    at ca.mcgill.mcb.pcingola.interval.Marker.<init>(Marker.java:37)
    at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLofDeletion(LossOfFunction.java:226)
    at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLof(LossOfFunction.java:155)
    at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLof(LossOfFunction.java:115)
    at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:170)
    at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
    at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
    at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
    at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.printSection(OutputFormatter.java:145)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:271)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:446)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:138)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:978)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:136)
Error: Error while processing VCF entry (line 95) :
    chromosome_1    16519   .   AAGAG   A   4961.97 .   AC=1;AF=1.00;AN=1;BaseQRankSum=-0.852;ClippingRankSum=0.599;DP=144;FS=17.672;MLEAC=1;MLEAF=1.00;MQ=38.60;MQRankSum=1.609;QD=30.85;ReadPosRankSum=-0.200;SOR=9.507;ANN=A|upstream_gene_variant|MODIFIER|Cre01.g000017|Cre01.g000017.v5.5|transcript|Cre01.g000017.t1.1.v5.5|protein_coding||c.-3429_-3426delAGAG|||||2246|WARNING_TRANSCRIPT_NO_START_CODON,A|upstream_gene_variant|MODIFIER|Cre01.g000033|Cre01.g000033.v5.5|transcript|Cre01.g000033.t1.1.v5.5|protein_coding||c.-3878_-3875delAGAG|||||3836|,A|intergenic_region|MODIFIER|Cre01.g000017|Cre01.g000017.v5.5|intergenic_region|Cre01.g000017.v5.5|||n.16520_16523delAGAG||||||  GT:AD:DP:GQ:PL  1:3,115:118:99:5001,0
java.lang.RuntimeException: Interval error: end before start.
    Class        : Marker
    Start        : 19948
    End          : 19161
    ID           : 
    Parent class : Chromosome
    Parent       : 1    0-8033584 CHROMOSOME '1'
java.lang.RuntimeException: Interval error: end before start.
    Class        : Marker
    Start        : 19948
    End          : 19161
    ID           : 
    Parent class : Chromosome
    Parent       : 1    0-8033584 CHROMOSOME '1'
    at ca.mcgill.mcb.pcingola.interval.Interval.<init>(Interval.java:38)
    at ca.mcgill.mcb.pcingola.interval.Marker.<init>(Marker.java:37)
    at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLofDeletion(LossOfFunction.java:226)
    at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLof(LossOfFunction.java:155)
    at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLof(LossOfFunction.java:115)
    at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:170)
    at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
    at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
    at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
    at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.printSection(OutputFormatter.java:145)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:278)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:446)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:138)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:978)
    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:136)

**Comment by pcingola** [comment]
Closing old issues.
