### ISSUE TITLE
 Cannot parse EffectType 'transcript'

### ISSUE THREAD

**Issue by martiliasf** [pcingola/SnpEff#138]
Trying to filter missense_variant and stop_gained

```java -Xmx14g -jar SnpSift.jar filter "(ANN[*].EFFECT has 'missense_variant') || (ANN[*].EFFECT has 'stop_gained')"```

Exception in thread "main" java.lang.RuntimeException: Cannot parse EffectType 'transcript'
        at ca.mcgill.mcb.pcingola.snpEffect.EffectType.parse(EffectType.java:100)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.parseEffect(VcfEffect.java:885)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.parseAnn(VcfEffect.java:734)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.parse(VcfEffect.java:718)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:134)
        at ca.mcgill.mcb.pcingola.vcf.VcfEntry.getVcfEffects(VcfEntry.java:621)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.FieldEff.getFieldString(FieldEff.java:49)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.Field.eval(Field.java:69)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.ExpressionBinary.eval(ExpressionBinary.java:25)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.ExpressionBinary.eval(ExpressionBinary.java:25)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdFilter.evaluate(SnpSiftCmdFilter.java:133)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:299)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:269)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSift.run(SnpSift.java:372)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSift.main(SnpSift.java:70)

SnpSift version 4.2 (build 2015-12-05), by Pablo Cingolani

error occurs with both java 1.7 and 1.8

**Comment by pcingola** [comment]
I'm pretty sure this was solved long time ago. Otherwise, please re-open.
