### ISSUE TITLE
java.lang.RuntimeException: Interval has negative coordinates

### ISSUE THREAD

**Issue by ghost** [pcingola/SnpEff#150]
Hi,

Recently, I am getting this error when I am running snpEff:

"Error: Error while processing VCF entry (line 754) :
        scaffold_148    4       .       CC      CCAATTTGGCTGAACGCCCACC  20.81   .       AC=2;AD=0,2;ADF=0,2;ADR=0,0;AN=2;DP=2;DP4=0,0,2,0;IDV=1;IMF=0.5;INDEL;MQ=23;MQ0F=0;SGB=0.36652;VDB=0.26 GT:AD:ADF:ADR:DP:PL:SP  ./.:0,0:0,0:0,0:0:0,0,0:0    ./.:0,0:0,0:0,0:0:0,0,0:0       ./.:0,0:0,0:0,0:0:0,0,0:0       ./.:0,0:0,0:0,0:0:0,0,0:0       ./.:0,0:0,0:0,0:0:0,0,0:0       ./.:0,0:0,0:0,0:0:0,0,0:0       ./.:0,0:0,0:0,0:0:0,0,0:0       1/1:0,2:0,2:0,0:2:42,6,0:0      ./.:0,0:0,0:0,0:0:0,0,0:0    ./.:0,0:0,0:0,0:0:0,0,0:0
java.lang.RuntimeException: Interval has negative coordinates.
        Class        : Marker
        Start        : -15
        End          : 4
        ID           :
        Parent class : Chromosome
        Parent       : scaffold_148     0-411 CHROMOSOME 'scaffold_148'
java.lang.RuntimeException: Interval has negative coordinates.
        Class        : Marker
        Start        : -15
        End          : 4
        ID           :
        Parent class : Chromosome
        Parent       : scaffold_148     0-411 CHROMOSOME 'scaffold_148'
        at ca.mcgill.mcb.pcingola.interval.Interval.<init>(Interval.java:47)
        at ca.mcgill.mcb.pcingola.interval.Marker.<init>(Marker.java:36)
        at ca.mcgill.mcb.pcingola.snpEffect.HgvsDna.isDuplication(HgvsDna.java:117)
        at ca.mcgill.mcb.pcingola.snpEffect.HgvsDna.toString(HgvsDna.java:328)
        at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.getHgvsDna(VariantEffect.java:508)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.set(VcfEffect.java:1010)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:260)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:121)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:297)
        at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:111)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:241)
        at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.printSection(OutputFormatter.java:144)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.iterateVcf(SnpEffCmdEff.java:354)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.runAnalysis(SnpEffCmdEff.java:807)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:726)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:678)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:773)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:126)
"

I have created a database and have used it with other data and it ran fine, but with one data I am getting this error.

The command I have used is:
java -jar snpEff-4.1/snpEff.jar  eff B73_RefGen_v3 -ud 0 ABC.vcf -s ABC.html -o GATK > snpEff_ABC.vcf

I am using snpEff-4.1.

Please help me figure out this.
I have used the same thing several times in the past few weeks but this error just came with this data.

Thanks!!!

**Comment by pcingola** [comment]
Closing old issues.
