### ISSUE TITLE
SnpEff 4.3 Macaca fascicularis, Interval error: end before start

### ISSUE THREAD

**Issue by mjafin** [pcingola/SnpEff#154]
Hi Pablo,
I'm getting the following error with the newly built SnpEff 4.3 Macaca fascicularis database:
```
[2016-10-21T16:13Z] uk2as123.medimmune.com: Error: Error while processing VCF entry (line 8387) :
[2016-10-21T16:13Z] uk2as123.medimmune.com:     chr1    38571   .       CAAAAAAATTTTA   C       268.73  .       AC=
1;AF=0.500;AN=2;BaseQRankSum=1.288;ClippingRankSum=-1.111;DP=18;FS=1.957;MLEAC=1;MLEAF=0.500;MQ=56.87;MQ0=0;MQRankS
um=-0.311;QD=14.93;ReadPosRankSum=-0.998;SOR=1.015;ANN=C|upstream_gene_variant|MODIFIER|PGBD2|gene1|transcript|XM_0
05539510.2|protein_coding||c.-24708_-24697delAAAAAAATTTTA|||||4829|WARNING_TRANSCRIPT_NO_START_CODON,C|upstream_gen
e_variant|MODIFIER|PGBD2|gene1|transcript|XM_005539512.2|protein_coding||c.-14905_-14894delAAAAAAATTTTA|||||4829|WA
RNING_TRANSCRIPT_NO_START_CODON,C|upstream_gene_variant|MODIFIER|PGBD2|gene1|transcript|XM_005539513.2|protein_codi
ng||c.-24707_-24696delAAAAAAATTTTA|||||4829|WARNING_TRANSCRIPT_NO_START_CODON,C|downstream_gene_variant|MODIFIER|id
8|GENE_id8|transcript|rna2|protein_coding||c.*5599_*5610delTAAAATTTTTTT|||||4829|,C|downstream_gene_variant|MODIFIE
R|id5|GENE_id5|transcript|rna1|protein_coding||c.*5599_*5610delTAAAATTTTTTT|||||4829|,C|downstream_gene_variant|MODIFIER|id2|GENE_id2|transcript|rna0|protein_coding||c.*5599_*5610delTAAAATTTTTTT|||||4829|,C|intergenic_region|MODIFIER|LOC102116409-id8|gene0-GENE_id8|intergenic_region|gene0-GENE_id8|||n.38572_38583delAAAAAAATTTTA|||||| GT:AD:DP:GQ:PL  0/1:10,8:18:99:306,0,396
[2016-10-21T16:13Z] uk2as123.medimmune.com: java.lang.RuntimeException: Interval error: end before start.
[2016-10-21T16:13Z] uk2as123.medimmune.com:     Class        : Marker
[2016-10-21T16:13Z] uk2as123.medimmune.com:     Start        : 63279
[2016-10-21T16:13Z] uk2as123.medimmune.com:     End          : 43400
[2016-10-21T16:13Z] uk2as123.medimmune.com:     ID           :
[2016-10-21T16:13Z] uk2as123.medimmune.com:     Parent class : Chromosome
[2016-10-21T16:13Z] uk2as123.medimmune.com:     Parent       : 1        0-227556263 CHROMOSOME '1'
[2016-10-21T16:13Z] uk2as123.medimmune.com: java.lang.RuntimeException: Interval error: end before start.
[2016-10-21T16:13Z] uk2as123.medimmune.com:     Class        : Marker
[2016-10-21T16:13Z] uk2as123.medimmune.com:     Start        : 63279
[2016-10-21T16:13Z] uk2as123.medimmune.com:     End          : 43400
[2016-10-21T16:13Z] uk2as123.medimmune.com:     ID           :
[2016-10-21T16:13Z] uk2as123.medimmune.com:     Parent class : Chromosome
[2016-10-21T16:13Z] uk2as123.medimmune.com:     Parent       : 1        0-227556263 CHROMOSOME '1'
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.interval.Interval.<init>(Interval.java:38)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.interval.Marker.<init>(Marker.java:38)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.LossOfFunction.isLofDeletion(LossOfFunction.java:232)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.LossOfFunction.isLof(LossOfFunction.java:155)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.LossOfFunction.isLof(LossOfFunction.java:115)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.LossOfFunction.isLof(LossOfFunction.java:115)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:170)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.outputFormatter.OutputFormatter.printSection(OutputFormatter.java:145)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:280)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:450)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:140)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:992)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:947)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.SnpEff.run(SnpEff.java:1009)
[2016-10-21T16:13Z] uk2as123.medimmune.com:     at org.snpeff.SnpEff.main(SnpEff.java:155)
[2016-10-21T16:13Z] uk2as123.medimmune.com: Uncaught exception occurred
```

Here's the command used for the run:
```
export PATH=/sge-data/apps/bcbio-nextgen/0.9.9/rhel6-x64/anaconda/bin:$PATH &&  /informatics/bcbio-nextgen/0.9.9/rhel6-x64/anaconda/bin/snpEff -Xms750m -Xmx4g -Djava.io.tmpdir=/sge-data/data/harario/bcbio_run/wgsbatch4/work/gatk-haplotype/tx/tmpvkdV_Z/tmp eff -dataDir /informatics/bcbio_genomes/Mfascicularis/Macaca_fascicularis_5/snpeff  -noLog -i vcf -o vcf -s /sge-data/data/harario/bcbio_run/wgsbatch4/work/gatk-haplotype/15C-effects-stats.html Macaca_fascicularis /sge-data/data/harario/bcbio_run/wgsbatch4/work/gatk-haplotype/15C.vcf.gz | /informatics/bcbio-nextgen/0.9.9/rhel6-x64/anaconda/bin/pbgzip -n 8  -c > /sge-data/data/harario/bcbio_run/wgsbatch4/work/gatk-haplotype/tx/tmpvkdV_Z/15C-effects.vcf.gz
```

Any ideas?

**Comment by trutane** [comment]
I get the same error using a custom-built homo sapiens database with snpEff v4.3 (snpEff_v4_3_core.zip, 2016-07-04). The trouble seems to be occurring in the **loss of function annotation** code. One can avoid the error with a "-noLof" command-line option, though this will cause snpEff to not add the LOF and nonsense mediated decay (NMD) tags.

Btw, this error is similar to the one reported in #128 which was related to HGVS annotation.
Here's a [gist containing a VCF snippet](https://gist.github.com/trutane/206ee5aa8350bc4e3ce1a181d228e583) with a variant that causes snpEff to throw this error. My error message is the following:

```
java.lang.RuntimeException: Interval error: end before start.
        Class        : Marker
        Start        : 879960
        End          : 861120
        ID           :
        Parent class : Chromosome
        Parent       : 1        0-249250620 CHROMOSOME '1'
        at ca.mcgill.mcb.pcingola.interval.Interval.<init>(Interval.java:38)
        at ca.mcgill.mcb.pcingola.interval.Marker.<init>(Marker.java:37)
        at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLofDeletion(LossOfFunction.java:226)
        at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLof(LossOfFunction.java:155)
        at ca.mcgill.mcb.pcingola.snpEffect.LossOfFunction.isLof(LossOfFunction.java:115)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:170)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
        at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
        at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.printSection(OutputFormatter.java:145)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:271)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:446)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:138)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:978)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:136)
Error: Error while processing VCF entry (line 98) :
        1       880639  25      TC      T       248.73  PASS    AC=1;AF=0.5;AN=2;BaseQRankSum=0.337;ClippingRankSum=0.048;DB;DP=18;FS=0.0;MLEAC=1;MLEAF=0.5;MQ=60.0;MQRankSum=0.433;QD=14.63;ReadPosRankSum=-0.529;SOR=0.804;EFF=downstream_gene_variant(MODIFIER||1107|n.*1107delC||GENE_id212||NON_CODING|rna43||T),downstream_gene_variant(MODIFIER||1107|n.*1107delC||GENE_id225||NON_CODING|rna44||T),downstream_gene_variant(MODIFIER||686|c.*1107delC|666|GENE_id150|protein_coding|CODING|rna38||T),downstream_gene_variant(MODIFIER||686|c.*1107delC|714|GENE_id164|protein_coding|CODING|rna39||T),downstream_gene_variant(MODIFIER||686|c.*1107delC|665|GENE_id177|protein_coding|CODING|rna40||T),downstream_gene_variant(MODIFIER||686|c.*1107delC|572|GENE_id191|protein_coding|CODING|rna41||T),downstream_gene_variant(MODIFIER||686|c.*934delC|395|GENE_id203|protein_coding|CODING|rna42||T),downstream_gene_variant(MODIFIER||679|c.*19519delC|0|gene36|protein_coding|CODING|NM_152486.2||T|WARNING_TRANSCRIPT_NO_START_CODON),downstream_gene_variant(MODIFIER||679|c.*1107delC|681|GENE_id238|protein_coding|CODING|rna45||T),downstream_gene_variant(MODIFIER||1107|n.*20647delC||gene36||CODING|XR_241028.1||T),downstream_gene_variant(MODIFIER||1107|n.*20647delC||gene36||CODING|XR_241029.1||T),downstream_gene_variant(MODIFIER||686|c.*20647delC|0|gene36|protein_coding|CODING|XM_005244723.1||T|WARNING_TRANSCRIPT_NO_START_CODON),downstream_gene_variant(MODIFIER||686|c.*20647delC|0|gene36|protein_coding|CODING|XM_005244724.1||T|WARNING_TRANSCRIPT_NO_START_CODON),downstream_gene_variant(MODIFIER||686|c.*20647delC|0|gene36|protein_coding|CODING|XM_005244725.1||T|WARNING_TRANSCRIPT_NO_START_CODON),downstream_gene_variant(MODIFIER||686|c.*20647delC|0|gene36|protein_coding|CODING|XM_005244726.1||T|WARNING_TRANSCRIPT_NO_START_CODON),downstream_gene_variant(MODIFIER||686|c.*20647delC|0|gene36|protein_coding|CODING|XM_005244727.1||T|WARNING_TRANSCRIPT_NO_START_CODON),intron_variant(MODIFIER|||c.2054-114delG|749|GENE_id252|protein_coding|CODING|rna46|17|T),intron_variant(MODIFIER|||c.2054-114delG|754|GENE_id271|protein_coding|CODING|rna47|17|T),non_coding_transcript_variant(MODIFIER||||0|gene37|protein_coding|CODING|NM_015658.3||T|WARNING_TRANSCRIPT_NO_START_CODON),non_coding_transcript_variant(MODIFIER||||0|gene37|protein_coding|CODING|XM_005244739.1||T|WARNING_TRANSCRIPT_NO_START_CODON)     GT:GATK:AD:DP:GQ:PL     0/1:0/1:8,9:17:99:286,0,248 
```
My snpEff command:

````
java -Xmx8G -jar snpEff.jar eff  -v  -formatEff  -geneId  -hgvs  -sequenceOntology  -noLof  -ud 5000 GRCh37p13.NCBI test.vcf 
````

**Comment by mjafin** [comment]
@pcingola any thoughts on this?

**Comment by pcingola** [comment]
I've just run the Macaca_fascicularis VCF using 4.3A and it works OK. Same when using Steve's VCF line (I used hg19 and GRCh37.75 instead since I don't have your build).

I'll release 4.3A this weekend.

**Comment by mjafin** [comment]
Very nice, will give it a go on Monday
