### ISSUE TITLE
SnpSift-4.3g cannnot parse SnpEff-4.2 annotation (build 2015-12-05)

### ISSUE THREAD

**Issue by mmokrejs** [pcingola/SnpEff#158]
Hi Pablo,
  is the current version incompatible with output of a previous version of SnpEff?

```
java -jar SnpSift.jar filter '( ( QUAL >= 24 ) & ( (EFF[*].IMPACT == '\''HIGH'\'') | (EFF[*].IMPACT == '\''MODERATE'\'') | ( ANN[*].IMPACT == '\''HIGH'\'' ) | ( ANN[*].IMPACT == '\''MEDIUM'\'' ) | ( ANN[*].EFFECT == '\''5_prime_UTR_premature start_codon_gain_variant'\'' ) | ( ANN[*].EFFECT == '\''start_retained'\'' ) | ( ANN[*].EFFECT == '\''regulatory_region_variant'\'' ) ) )' myfile.gatk.HaplotypeCaller.SnpEff.vcf
Exception in thread "main" java.lang.RuntimeException: Error parsing:
        'PROTEIN_INTERACTION_LOCUS(HIGH||||AK2|protein_coding|CODING||6)'
         EFF formatVersion : FORMAT_EFF_2
        0 : 'PROTEIN_INTERACTION_LOCUS'
        1 : 'HIGH'
        2 : ''
        3 : ''
        4 : ''
        5 : 'AK2'
        6 : 'protein_coding'
        7 : 'CODING'
        8 : ''
        9 : '6'
        10 : ''

        at org.snpeff.vcf.VcfEffect.parseEff(VcfEffect.java:866)
        at org.snpeff.vcf.VcfEffect.parse(VcfEffect.java:719)
        at org.snpeff.vcf.VcfEffect.<init>(VcfEffect.java:134)
        at org.snpeff.vcf.VcfEntry.getVcfEffects(VcfEntry.java:718)
        at org.snpsift.lang.expression.FieldEff.getFieldString(FieldEff.java:49)
        at org.snpsift.lang.expression.Field.eval(Field.java:76)
        at org.snpsift.lang.expression.ExpressionBinary.eval(ExpressionBinary.java:25)
        at org.snpsift.lang.expression.Or.eval(Or.java:19)
        at org.snpsift.lang.expression.Or.eval(Or.java:19)
        at org.snpsift.lang.expression.Or.eval(Or.java:19)
        at org.snpsift.lang.expression.Or.eval(Or.java:19)
        at org.snpsift.lang.expression.Or.eval(Or.java:19)
        at org.snpsift.lang.expression.Or.eval(Or.java:19)
        at org.snpsift.lang.expression.And.eval(And.java:26)
        at org.snpsift.SnpSiftCmdFilter.evaluate(SnpSiftCmdFilter.java:132)
        at org.snpsift.SnpSiftCmdFilter.annotate(SnpSiftCmdFilter.java:89)
        at org.snpsift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:336)
        at org.snpsift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:312)
        at org.snpsift.SnpSift.run(SnpSift.java:401)
        at org.snpsift.SnpSift.main(SnpSift.java:74)
Caused by: java.lang.RuntimeException: Cannot parse EffectType 'PROTEIN_INTERACTION_LOCUS'
        at org.snpeff.snpEffect.EffectType.parse(EffectType.java:125)
        at org.snpeff.vcf.VcfEffect.parseEffect(VcfEffect.java:888)
        at org.snpeff.vcf.VcfEffect.parseEff(VcfEffect.java:801)
        ... 19 more

```

**Comment by mmokrejs** [comment]
Here is another case:

```
Exception in thread "main" java.lang.RuntimeException: Error parsing:
        'PROTEIN_INTERACTION_LOCUS(HIGH||||ALDH4A1|protein_coding|CODING||13)'
         EFF formatVersion : FORMAT_EFF_2
        0 : 'PROTEIN_INTERACTION_LOCUS'
        1 : 'HIGH'
        2 : ''
        3 : ''
        4 : ''
        5 : 'ALDH4A1'
        6 : 'protein_coding'
        7 : 'CODING'
        8 : ''
        9 : '13'
        10 : ''
```

`
chr1    18875434        rs2230709       C       T       805.77  .       AC=1;AF=0.500;AN=2;BaseQRankSum=-4.186;ClippingRankSum=0.000;DB;DP=49;ExcessHet=3.0103;FS=2.504;MLEAC=1;MLEAF=0.500;MQ=60.95;MQRankSum=0.872;QD=16.44;ReadPosRankSum=2.127;SOR=0.481;EFF=PROTEIN_INTERACTION_LOCUS(HIGH||||ALDH4A1|protein_coding|CODING||13)      GT:AD:DP:GQ:PL  0/1:20,29:49:99:834,0,613`

**Comment by BTessoulin** [comment]
Hi, seems to be quite the same here: etiher with the extractField or the filter functions, while the snpEff version used to annotate the variants was 4.0, and is still the version used here to filter/extract:

```
java -jar ./SnpSift.jar filter "(EFF[*].GENE='TP53')" OPM2.vcf.gz >filtered.vcf
Exception in thread "main" java.lang.RuntimeException: Error parsing:
	'inframe_insertion(MODERATE||aga/aAAGAAAga|p.Arg127_Glu128insLysGluArg/c.379_380insAAGAAA|780|CDK11A|protein_coding|CODING|ENST00000404249|5|1)'
	 EFF formatVersion : FORMAT_EFF_4
	0 : 'inframe_insertion'
	1 : 'MODERATE'
	2 : ''
	3 : 'aga/aAAGAAAga'
	4 : 'p.Arg127_Glu128insLysGluArg/c.379_380insAAGAAA'
	5 : '780'
	6 : 'CDK11A'
	7 : 'protein_coding'
	8 : 'CODING'
	9 : 'ENST00000404249'
	10 : '5'
	11 : '1'
	12 : ''

	at org.snpeff.vcf.VcfEffect.parseEff(VcfEffect.java:866)
	at org.snpeff.vcf.VcfEffect.parse(VcfEffect.java:719)
	at org.snpeff.vcf.VcfEffect.<init>(VcfEffect.java:134)
	at org.snpeff.vcf.VcfEntry.getVcfEffects(VcfEntry.java:718)
	at org.snpsift.lang.expression.FieldEff.getFieldString(FieldEff.java:49)
	at org.snpsift.lang.expression.Field.eval(Field.java:76)
	at org.snpsift.lang.expression.ExpressionBinary.eval(ExpressionBinary.java:25)
	at org.snpsift.SnpSiftCmdFilter.evaluate(SnpSiftCmdFilter.java:132)
	at org.snpsift.SnpSiftCmdFilter.annotate(SnpSiftCmdFilter.java:89)
	at org.snpsift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:336)
	at org.snpsift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:312)
	at org.snpsift.SnpSift.run(SnpSift.java:401)
	at org.snpsift.SnpSift.main(SnpSift.java:74)
Caused by: java.lang.RuntimeException: Cannot parse EffectType 'inframe_insertion'
	at org.snpeff.snpEffect.EffectType.parse(EffectType.java:125)
	at org.snpeff.vcf.VcfEffect.parseEffect(VcfEffect.java:888)
	at org.snpeff.vcf.VcfEffect.parseEff(VcfEffect.java:801)

###############################################################################

java -jar ./SnpSift.jar extractFields merged.vcf.gz  CHROM ID EFF[1].GENE -e "." | head
CHROM	ID	EFF[1].GENE
1	.	WASH7P
1	.	WASH7P
1	rs201725126	WASH7P
1	rs200579949	WASH7P
1	.	WASH7P
1	.	WASH7P
1	.	WASH7P
1	.	WASH7P
1	.	DDX11L1
Exception in thread "main" java.lang.RuntimeException: Error parsing:
	'inframe_insertion(MODERATE||aga/aAAGAAAga|p.Arg127_Glu128insLysGluArg/c.379_380insAAGAAA|780|CDK11A|protein_coding|CODING|ENST00000404249|5|1)'
	 EFF formatVersion : FORMAT_EFF_4
	0 : 'inframe_insertion'
	1 : 'MODERATE'
	2 : ''
	3 : 'aga/aAAGAAAga'
	4 : 'p.Arg127_Glu128insLysGluArg/c.379_380insAAGAAA'
	5 : '780'
	6 : 'CDK11A'
	7 : 'protein_coding'
	8 : 'CODING'
	9 : 'ENST00000404249'
	10 : '5'
	11 : '1'
	12 : ''

	at org.snpeff.vcf.VcfEffect.parseEff(VcfEffect.java:866)
	at org.snpeff.vcf.VcfEffect.parse(VcfEffect.java:719)
	at org.snpeff.vcf.VcfEffect.<init>(VcfEffect.java:134)
	at org.snpeff.vcf.VcfEntry.getVcfEffects(VcfEntry.java:718)
	at org.snpsift.lang.expression.FieldEff.getFieldString(FieldEff.java:49)
	at org.snpsift.lang.expression.Field.eval(Field.java:76)
	at org.snpsift.SnpSiftCmdExtractFields.evaluate(SnpSiftCmdExtractFields.java:43)
	at org.snpsift.SnpSiftCmdExtractFields.run(SnpSiftCmdExtractFields.java:147)
	at org.snpsift.SnpSiftCmdExtractFields.run(SnpSiftCmdExtractFields.java:118)
	at org.snpsift.SnpSift.run(SnpSift.java:401)
	at org.snpsift.SnpSift.main(SnpSift.java:74)
Caused by: java.lang.RuntimeException: Cannot parse EffectType 'inframe_insertion'
	at org.snpeff.snpEffect.EffectType.parse(EffectType.java:125)
	at org.snpeff.vcf.VcfEffect.parseEffect(VcfEffect.java:888)
	at org.snpeff.vcf.VcfEffect.parseEff(VcfEffect.java:801)


```

Thanks!

**Comment by karthigayini** [comment]
I have similar problem too. Is there a fix ?

**Comment by pcingola** [comment]
SnpEff & SnpSift are compatible within same version.
The solution is very simple: Re-annotate the file using the same version.
