### ISSUE TITLE
Phase correction may produce exons with end < start

### ISSUE THREAD

**Issue by pcingola** [pcingola/SnpEff#16]
This may be the case reported in Maize genome, transcript AC208892.3_FGT005
which leads to errors when creating the summary (genes) file.

Caused by: java.lang.RuntimeException: Interval error: end before start. Start:216323401, End: 216323400
        at ca.mcgill.mcb.pcingola.interval.Interval.<init>(Interval.java:32)
        at ca.mcgill.mcb.pcingola.interval.Marker.<init>(Marker.java:31)
        at ca.mcgill.mcb.pcingola.interval.Markers.merge(Markers.java:221)
        at ca.mcgill.mcb.pcingola.interval.Gene.sizeof(Gene.java:385)
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)

After debugging, this is produced by:

start: 216323401    end:216323400
    2:21632 3452-216323702 'Exon_2_216323452_216323703', rank: 3, frame: 2, sequence: aggagagggaggtggtggtggagcaccagcaggaggagccgaggaggagggccccg
    2:21632 3401-216323400 'Exon_2_216323400_216323401', rank: 2, frame: 2, sequence:
    2:21632 3283-216323328 'Exon_2_216323284_216323329', rank: 1, frame: 0, sequence: atggcggaggaccagaccaaccccagcggcccagccccagcaagcg
    2:21632 3945-216324424 'Exon_2_216323946_216324425', rank: 4, frame: 0, sequence: caagggtttatttcgaggaatcaaattaacaacgatgtagtaacaggtgcacgagg

**Comment by Lingrui** [comment]
So how do you solve this question? 
Just skip the warning tips or modify the .gff file by hand to adapt to snpEff ?

**Comment by pcingola** [comment]
The code has been fixed and this particular issue does not happen any more.
No need to do anything.

**Comment by Lingrui** [comment]
@pcingola  Thank you. I have update to the lasted version and everything goes alright.
