### ISSUE TITLE
INFO field 'END' is before varaint's 'POS'

### ISSUE THREAD

**Issue by brentp** [pcingola/SnpEff#178]
This can happen when annotating SVs. It seems it's when the CIEND makes the min end < the POS.

given this valid vcf record:
```
1	24538586	34160	G	<DEL>	18.57	.	SVTYPE=DEL;SVLEN=8;END=24538578;STRANDS=+-:416;IMPRECISE;CIPOS=-338,263;CIEND=-309,292;CIPOS95=-271,263;CIEND95=-258,258;
```

snpEff gives:
```
VcfFileIterator.parseVcfLine(132):	Fatal error reading file 'svs.vcf.gz' (line: 2947):
... vcf line ...
java.lang.RuntimeException: java.lang.RuntimeException: INFO field 'END' is before varaint's 'POS'
	END : 24538577
	POS : 24538585
	at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:133)
	at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:184)
	at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:57)
	at org.snpeff.fileIterator.FileIterator.hasNext(FileIterator.java:123)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:467)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:142)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1029)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)
Caused by: java.lang.RuntimeException: INFO field 'END' is before varaint's 'POS'
	END : 24538577
	POS : 24538585
	at org.snpeff.vcf.VcfEntry.parseEnd(VcfEntry.java:1122)
	at org.snpeff.vcf.VcfEntry.parse(VcfEntry.java:962)
	at org.snpeff.vcf.VcfEntry.<init>(VcfEntry.java:219)
	at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:130)
	... 9 more
```

**Comment by pcingola** [comment]
Hi Brent,
  According to my understanding of the VCF spec, the POS coordinate should be before the END coordinate:

_"... If any of the ALT alleles is a symbolic allele (an angle-bracketed ID String “<ID>”) then the padding base is required and POS denotes the coordinate of the base preceding the polymorphism."_

  So, I think, that the VCF record you show is invalid.
  Let me know if you think this is not correct, and I'll fix the code accordingly (by removing the coordinate check).

**Comment by brentp** [comment]
Hi Pablo, thanks for following up. I found this occurred in 2 SVs out of ~200,000 and so I just flipped the start and end of those--they were sketchy SVs anyway. So I'll go ahead and close this.

**Comment by vyellapa** [comment]
Hi,
So this happens often with translocations using output from Delly. Any way around it?

Teja

**Comment by yaronmiz** [comment]
Hi, The swap of POS/END happens on SV files for INV - inversions..  and happens in least Manta caller:
##source=GenerateSVCandidates manta-0.23.1

Not sure if its a bug in Manta or if its a lack of standard for SVs.
I would be helpful if snpSift would ignore this by default or by a command line flag
