### ISSUE TITLE
Error building database with GFF3

### ISSUE THREAD

**Issue by royfrancis** [pcingola/SnpEff#193]
I have my genome fasta and genes as gff3 in such a directory structure.

```
.
├── data
│   └── dr.vega
│       ├── genes.gff
│       └── sequences.fa
├── examples/
├── galaxy/
├── scripts/
├── snpEff.config
├── snpEff.config.original
├── snpEff.jar
└── SnpSift.jar
```

I have added the following to my snpEff.config

```
# ZF VEGA AB
dr.vega.genome : zf
```

When I build, `java -jar snpEff.jar build -gff3 -v dr.vega`, I get the following error:

```
[rf@m1 snpEff]$ java -jar snpEff.jar build -gff3 -v dr.vega
00:00:00        SnpEff version SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani
00:00:00        Command: 'build'
00:00:00        Building database for 'dr.vega'
00:00:00        Reading configuration file 'snpEff.config'. Genome: 'dr.vega'
00:00:00        Reading config file: /pica/v9/b2016094_nobackup/ngs/programs/snpeff/snpEff/snpEff.config
00:00:00        done
Reading GFF3 data file  : '/pica/v9/b2016094_nobackup/ngs/programs/snpeff/snpEff/./data/dr.vega/genes.gff'
java.lang.RuntimeException: FATAL ERROR: Offending line (lineNum: 3): '1        gene    6408  12027    .       -       .       ID=OTTDARG00000032462;Name=OTTDARG00000032462;biotype=protein_coding;'. File '/pica/v9/b2016094_nobackup/ngs/programs/snpeff/snpEff/./data/dr.vega/genes.gff' line 3
        '1      gene    6408    12027   .       -       .       ID=OTTDARG00000032462;Name=OTTDARG00000032462;biotype=protein_coding;'

        at org.snpeff.snpEffect.factory.SnpEffPredictorFactory.error(SnpEffPredictorFactory.java:428)
        at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.readGff(SnpEffPredictorFactoryGff.java:508)
        at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:337)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:369)
        at org.snpeff.SnpEff.run(SnpEff.java:1183)
        at org.snpeff.SnpEff.main(SnpEff.java:162)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8
        at org.snpeff.interval.GffMarker.parse(GffMarker.java:268)
        at org.snpeff.interval.GffMarker.<init>(GffMarker.java:54)
        at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.parse(SnpEffPredictorFactoryGff.java:419)
        at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.readGff(SnpEffPredictorFactoryGff.java:502)
        ... 4 more
java.lang.RuntimeException: Error reading file '/pica/v9/b2016094_nobackup/ngs/programs/snpeff/snpEff/./data/dr.vega/genes.gff'
java.lang.RuntimeException: FATAL ERROR: Offending line (lineNum: 3): '1        gene    6408  12027    .       -       .       ID=OTTDARG00000032462;Name=OTTDARG00000032462;biotype=protein_coding;'. File '/pica/v9/b2016094_nobackup/ngs/programs/snpeff/snpEff/./data/dr.vega/genes.gff' line 3
        '1      gene    6408    12027   .       -       .       ID=OTTDARG00000032462;Name=OTTDARG00000032462;biotype=protein_coding;'

        at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:353)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:369)
        at org.snpeff.SnpEff.run(SnpEff.java:1183)
        at org.snpeff.SnpEff.main(SnpEff.java:162)
00:00:00        Logging
00:00:01        Checking for updates...
00:00:02        Done.
```

But, my GFF3 file seems to be fine.

```
[rf@m1 dr.vega]$ head genes.gff
##gff-version   3
##sequence-region       1       1       58871917
1       gene    6408    12027   .       -       .       ID=OTTDARG00000032462;Name=OTTDARG00000032462;biotype=protein_coding;
1       gene    11822   16373   .       +       .       ID=OTTDARG00000032461;Name=OTTDARG00000032461;biotype=protein_coding;
1       gene    18716   23389   .       +       .       ID=OTTDARG00000032463;Name=OTTDARG00000032463;biotype=protein_coding;
1       gene    27690   34330   .       +       .       ID=OTTDARG00000032473;Name=OTTDARG00000032473;biotype=protein_coding;
1       gene    36552   39191   .       +       .       ID=OTTDARG00000032472;Name=OTTDARG00000032472;biotype=protein_coding;
1       gene    39313   44565   .       -       .       ID=OTTDARG00000032471;Name=OTTDARG00000032471;biotype=protein_coding;
1       gene    44839   50247   .       -       .       ID=OTTDARG00000033607;Name=OTTDARG00000033607;biotype=protein_coding;
1       gene    60987   65017   .       -       .       ID=OTTDARG00000033606;Name=OTTDARG00000033606;biotype=protein_coding;
```

```
[rf@m1 dr.vega]$ tail genes.gff
AB      CDS     13106601        13106914        .       +       1       Name=OTTDARP00000003646;Parent=OTTDART00000003995;
AB      CDS     13128498        13128642        .       -       1       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
AB      CDS     13128202        13128382        .       -       2       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
AB      CDS     13123313        13123407        .       -       1       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
AB      CDS     13121050        13121145        .       -       1       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
AB      CDS     13120453        13120622        .       -       0       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
AB      CDS     13118012        13118071        .       -       0       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
AB      CDS     13117773        13117916        .       -       0       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
AB      CDS     13115647        13115738        .       -       2       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
AB      CDS     13115211        13115430        .       -       .       Name=OTTDARP00000003647;Parent=OTTDART00000003996;
```

**Comment by pcingola** [comment]
Hi Roy,
  I'm out of town now, but I'll try to take a look at it when I get back home.
Ping me again if you don't hear from me in a couple of weeks.

**Comment by royfrancis** [comment]
Hi, I have figured out that the issue was with the GFF3 file. Since I downloaded it from the Ensembl VEGA website, I never expected it to have problems. Turns out it was missing a field and many tools failed. With a new file, the database building works fine.

**Comment by Roopali87** [comment]
> Hi, I have figured out that the issue was with the GFF3 file. Since I downloaded it from the Ensembl VEGA website, I never expected it to have problems. Turns out it was missing a field and many tools failed. With a new file, the database building works fine.

Dear Roy Francis
Thank you for your post. I am experiencing the same issue in Cygwin. I followed the same steps as you and end up with the error as you got. Please advise me of steps you took to solve this. Your help is very much appreciated. Thank you.

**Comment by royfrancis** [comment]
It's been so long. I don't remember exactly what was wrong. Generally, check that the file fits to [GFF standards](https://m.ensembl.org/info/website/upload/gff3.html), all necessary fields are present, delimiter is correct etc.

**Comment by Roopali87** [comment]
Thank you for getting back to me, Roy. I suspect the same but I am beginner
to this world. I have to explore around to get to the point.

Regards
Roopali
