### ISSUE TITLE
Error downloading custom database from server, DB present according to download command

### ISSUE THREAD

**Issue by carburator** [pcingola/SnpEff#206]
Hello,

I built a database from my own genome, and checked that it was present on the snpEff server with:

java -jar snpEff.jar databases | grep -i Walnut

Walnut                                                      	Walnut                                                     http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_Walnut.zip

However, when I try to run the command:

java -jar /home/cary/bin/snpEff/snpEff.jar eff -c /home/cary/bin/snpEff/snpEff.config -i vcf -o vcf Walnut /mnt/gn3/gnome3/DropBox/Cary/walnut/mpileup-1.8/output_mpileup_1.8.vcf

I receive the following error:
00:00:00	ERROR while connecting to http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_Walnut.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:178)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1221)
	at org.snpeff.SnpEff.loadDb(SnpEff.java:515)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1001)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)
Caused by: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:127)
	... 9 more
java.lang.RuntimeException: Genome download failed!
	at org.snpeff.SnpEff.loadDb(SnpEff.java:516)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1001)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)

I do not see my file when I browse the database server at  http://downloads.sourceforge.net/project/snpeff/databases/v4_3/, even though the database command indicates the file is there.

Any thoughts?

Thanks

**Comment by pcingola** [comment]
Closing old issues.
