### ISSUE TITLE
Unable to download some databases with new SnpEff v5.0.0

### ISSUE THREAD

**Issue by gel001** [pcingola/SnpEff#248]
Greetings,

We are excited to check out SnpEff v5.0.0 but it appears that some of the databases we are interested in are not able to be downloaded right now.

If we look at the output of the "databases" command we can see the three we are interested in as being listed.

- GRCh38.p7.RefSeq
- GRCh37.p13.RefSeq
- GRCh37.87

```bash
java -jar snpEff.jar databases | grep GRCh38.p7.RefSeq
GRCh38.p7.RefSeq                                            	Human genome GRCh38 using RefSeq transcripts                	          	                              	https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.p7.RefSeq.zip

java -jar snpEff.jar databases | grep GRCh37.p13.RefSeq
GRCh37.p13.RefSeq                                           	Human genome GRCh37 using RefSeq transcripts                	          	                              	https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.p13.RefSeq.zip


java -jar snpEff.jar databases | grep GRCh37.87
GRCh37.87                                                   	Human genome GRCh37 using transcripts                       	          	                              	https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.87.zip
```

However, trying to download them returns errors:

```bash
 java -jar snpEff.jar download -v GRCh38.p7.RefSeq
00:00:00	SnpEff version SnpEff 5.0 (build 2020-08-09 21:23), by Pablo Cingolani
00:00:00	Command: 'download'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'GRCh38.p7.RefSeq'
00:00:00	Reading config file: /Users/gel001/Desktop/snpEff_5.0/snpEff.config
00:00:00	done
00:00:00	Downloading database for 'GRCh38.p7.RefSeq'
00:00:00	Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.p7.RefSeq.zip
00:00:01	ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.p7.RefSeq.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:178)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)
Caused by: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:127)
	... 5 more
00:00:01	Logging
00:00:02	Done.
```

```bash
java -jar snpEff.jar download -v GRCh37.p13.RefSeq
00:00:00	SnpEff version SnpEff 5.0 (build 2020-08-09 21:23), by Pablo Cingolani
00:00:00	Command: 'download'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'GRCh37.p13.RefSeq'
00:00:00	Reading config file: /Users/gel001/Desktop/snpEff_5.0/snpEff.config
00:00:00	done
00:00:00	Downloading database for 'GRCh37.p13.RefSeq'
00:00:00	Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.p13.RefSeq.zip
00:00:00	ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.p13.RefSeq.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:178)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)
Caused by: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:127)
	... 5 more
00:00:00	Logging
00:00:01	Done.
```

```bash
java -jar snpEff.jar download -v GRCh37.87
00:00:00	SnpEff version SnpEff 5.0 (build 2020-08-09 21:23), by Pablo Cingolani
00:00:00	Command: 'download'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'GRCh37.87'
00:00:00	Reading config file: /Users/gel001/Desktop/snpEff_5.0/snpEff.config
00:00:00	done
00:00:00	Downloading database for 'GRCh37.87'
00:00:00	Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.87.zip
00:00:00	ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh37.87.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:178)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)
Caused by: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:127)
	... 5 more
00:00:00	Logging
00:00:01	Done.
```

I did some poking around the blob store (although I may have been doing it wrong, I am more of an AWS guy) and I didn't see them listed under any kind of alternate either.

```bash
curl https://snpeff.blob.core.windows.net/databases?restype=container&comp=list&prefix=v5_0 > databases.xml 
```

Is it possible some automated deployment croaked when uploading them? Downloading other ones, like "hg19" works just fine.

Thanks!

**Comment by pcingola** [comment]
OK, looks like I need to rebuild and upload those. Thank you for the heads-up

**Comment by aardes** [comment]
Hi,

@pcingola  Do you have an update for this, I have the same issue.

regards

**Comment by Phillip-a-richmond** [comment]
+1 on this issue as well. Perhaps worth staying with 4.3?

**Comment by pcingola** [comment]
GRCh37.p13.RefSeq ahs been uploaded.

**Comment by pcingola** [comment]
GRCh38.p13.RefSeq ahs been uploaded.
GRCh37.75 is also available.
