### ISSUE TITLE
java.lang.RuntimeException: java.lang.RuntimeException: WARNING: Unkown IUB code for SNP '0'

### ISSUE THREAD

**Issue by moldach** [pcingola/SnpEff#267]
I'm getting an error when running `SnpEff` on `VarScan2.3.9` data:

## Command  
```
$ java -jar /opt/snpeff/snpeff/snpEff.jar \
     -dataDir /home/moldach/wrappers/MTG-workflows/resources/snpeff \
     -stats MTG324.html \
     -csvStats MTG324.csv \
      WBcel235.86 \
      MTG324.vcf > MTG324.annotated.vcf
```

## Error

```
VcfFileIterator.parseVcfLine(132):      Fatal error reading file 'variant_calling/varscan2/bwa-mem2/sambamba/picard/MTG324.vcf' (line: 2):
I       3171890 C       T       0       5       100%    0       1       0       37      0.98    0       1       0       0       0       5       T
java.lang.RuntimeException: java.lang.RuntimeException: WARNING: Unkown IUB code for SNP '0'
        at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:133)
        at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:184)
        at org.snpeff.fileIterator.VcfFileIterator.readNext(VcfFileIterator.java:57)
        at org.snpeff.fileIterator.FileIterator.hasNext(FileIterator.java:123)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:464)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:142)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1026)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:981)
        at org.snpeff.SnpEff.run(SnpEff.java:1182)
        at org.snpeff.SnpEff.main(SnpEff.java:162)
Caused by: java.lang.RuntimeException: WARNING: Unkown IUB code for SNP '0'
        at org.snpeff.vcf.VcfEntry.parseAltSingle(VcfEntry.java:1104)
        at org.snpeff.vcf.VcfEntry.parseAlts(VcfEntry.java:979)
        at org.snpeff.vcf.VcfEntry.parse(VcfEntry.java:947)
        at org.snpeff.vcf.VcfEntry.<init>(VcfEntry.java:219)
        at org.snpeff.fileIterator.VcfFileIterator.parseVcfLine(VcfFileIterator.java:130)
        ... 9 more
```

**Comment by pcingola** [comment]
The VCF entry is corrupted. Make sure your VCF is properly formatted: https://samtools.github.io/hts-specs/VCFv4.3.pdf
In your case, the ID column seems to be missing.
