### ISSUE TITLE
java.lang.RuntimeException: java.io.FileNotFoundException: /tmp/snpEff_v5_0_GRCh38.99.zip (No such file or directory)

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [pcingola/SnpEff#268]
I'm using snpeff 5.0 installed from miniconda in a snakemake workflow inside a docker container whose base image is the official miniconda image (debian-based).

Below is a snippet of the error that I'm getting when trying to annoate vcfs with snpeff. The script downloads grch38, then deletes the zip file, then complains that it can't find zip file.

Any help is appreciated! 

```bash
00:00:04	Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_GRCh38.99.zip
00:00:05	Local file name: '/tmp/snpEff_v5_0_GRCh38.99.zip'
00:00:05	Local file name: '/tmp/snpEff_v5_0_GRCh38.99.zip'
........................................................................................................................................................................................................................bix.go:251: chromosome chrM not found in data/cosmic/hg38/CosmicCodingMuts_hg38.vcf.gz
bix.go:251: chromosome chrM not found in data/civic/hg38/civic.vcf.gz
........bix.go:251: chromosome chrY not found in data/civic/hg38/civic.vcf.gz
bix.go:251: chromosome chrY not found in data/civic/hg38/civic.vcf.gz
vcfanno.go:248: annotated 64520 variants in 84.47 seconds (763.8 / second)
[32m[Thu Nov 12 17:05:43 2020][0m
[32mFinished job 4.[0m
[32m1 of 6 steps (17%) done[0m
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
00:07:00	Donwload finished. Total 610699657 bytes.
00:07:00	Extracting file 'data/GRCh38.99/pwms.bin'
00:07:00	Creating local directory: '/opt/conda/share/snpeff-5.0-0/./data/GRCh38.99'
00:07:00	Extracting file 'data/GRCh38.99/sequence.1.bin'
.00:07:00	Extracting file 'data/GRCh38.99/sequence.10.bin'
00:07:00	Extracting file 'data/GRCh38.99/sequence.11.bin'
00:07:00	Extracting file 'data/GRCh38.99/sequence.12.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.13.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.14.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.15.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.16.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.17.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.18.bin'
.00:07:01	Extracting file 'data/GRCh38.99/sequence.19.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.2.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.20.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.21.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.22.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.3.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.4.bin'
00:07:01	Extracting file 'data/GRCh38.99/sequence.5.bin'
00:07:02	Extracting file 'data/GRCh38.99/sequence.6.bin'
00:07:02	Extracting file 'data/GRCh38.99/sequence.7.bin'
.00:07:02	Extracting file 'data/GRCh38.99/sequence.8.bin'
00:07:02	Extracting file 'data/GRCh38.99/sequence.9.bin'
00:07:02	Extracting file 'data/GRCh38.99/sequence.X.bin'
00:07:02	Extracting file 'data/GRCh38.99/sequence.Y.bin'
00:07:02	Extracting file 'data/GRCh38.99/sequence.bin'
00:07:02	Extracting file 'data/GRCh38.99/snpEffectPredictor.bin'
.00:07:03	Extracting file 'data/GRCh38.99/cytoBand.txt.gz'
00:07:03	Unzip: OK
00:07:03	Deleted local file '/tmp/snpEff_v5_0_GRCh38.99.zip'
00:07:03	Done
00:07:03	Database installed.
......
00:07:06	Donwload finished. Total 610699657 bytes.
java.lang.RuntimeException: java.io.FileNotFoundException: /tmp/snpEff_v5_0_GRCh38.99.zip (No such file or directory)
	at org.snpeff.util.Download.unzip(Download.java:296)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:33)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1233)
	at org.snpeff.SnpEff.loadDb(SnpEff.java:520)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:922)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)
```

**Comment by pcingola** [comment]
The download command works OK in SnpEff. This is not a SnpEff bug.
It seems to be a problem related you your particular install, your docker container, or your snakemake workflow.
