### ISSUE TITLE
ERROR while connecting to server

### ISSUE THREAD

**Issue by chiahuichou** [pcingola/SnpEff#280]
Hi,

I recently installed the snpEff v5.0.0, and when I tried to download the Arabidopsis thaliana database using 

`$java -jar snpEff.jar download -v Arabidopsis_thaliana`

the error message showed up:

```
00:00:00	SnpEff version SnpEff 5.0 (build 2020-08-09 21:23), by Pablo Cingolani
00:00:00	Command: 'download'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'Arabidopsis_thaliana'
00:00:00	Reading config file: /Users/chiahuichou/Desktop/snpeff-5.0-0/share/snpeff-5.0-0/snpEff.config
00:00:01	done
00:00:01	Downloading database for 'Arabidopsis_thaliana'
00:00:01	Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Arabidopsis_thaliana.zip
00:00:02	ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Arabidopsis_thaliana.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:178)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)
Caused by: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:127)
	... 5 more
00:00:02	Logging
00:00:03	Done.
```

Thanks!

**Comment by pcingola** [comment]
This should have been solved by now. I'm closing the issue, please reopen if you see this error again.
