### ISSUE TITLE
Having trouble using downloaded database

### ISSUE THREAD

**Issue by aditisk** [pcingola/SnpEff#288]
Hello SnpEff team,

I'm a new user so apologize if my question is naive. I am using the pre-built GRCh38.86 database. I downloaded this to my local directory since I don't have permission on our computing cluster to download it to the same directory as the SnpEff installation. When I am trying to use this downloaded database, I get the error as seen below:

`java.lang.RuntimeException: Property: '/zfs1/rferris/adk85/Zandberg_0001-WES/GRCh38.86.genome' not found
        at org.snpeff.interval.Genome.<init>(Genome.java:106)
        at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:681)
        at org.snpeff.snpEffect.Config.readConfig(Config.java:649)
        at org.snpeff.snpEffect.Config.init(Config.java:480)
        at org.snpeff.snpEffect.Config.<init>(Config.java:117)
        at org.snpeff.SnpEff.loadConfig(SnpEff.java:451)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1000)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
        at org.snpeff.SnpEff.run(SnpEff.java:1183)
        at org.snpeff.SnpEff.main(SnpEff.java:162)`

I went through the documentation and I was under the impression that no extra steps are needed if I am using a pre-built database. Am I missing something here ? How can I get past this error ? 

Thank you so much.

**Comment by pcingola** [comment]
The message says that the specific entry does not exist in the configuration file `snpEff.config`

If you are using the latest version (5.0d at this time), the human genome database would be `GRCh38.99` (instead of `GRCh38.86` which is the older version you are trying to use).

Try using the latest SnpEff version (5.0d) and downloading (using the `download` command):
```
java -jar snpEff.jar download -v GRCh38.99 
```
The database will be installed in the `data` directory specified in SnpEff's config file. If you don't have write permissions, then you can either:
1. Install a local SnpEff version in a directory you own/can write to (maybe `$HOME/snpEff`?)
2. Create an alternative `snpEff.config` to point to your own `data` directory where you installed the database

I hope this helps.
Closing the issue, feel free to re-open.

**Comment by aditisk** [comment]
Hi @pcingola, thanks for your help. I was able to run SnpEff with no errors.
