### ISSUE TITLE
pre-built database download error: UnknownHostException

### ISSUE THREAD

**Issue by JeffreyCifello** [pcingola/SnpEff#297]
Hello,

I am attempting to download a database associated with snpEff v4_3, and running into an error addressed in [this issue](https://github.com/pcingola/SnpEff/issues/294), where the server appears to be offline and the same exception is thrown. 

I first obtained this version using: 
```
wget https://sourceforge.net/projects/snpeff/files/snpEff_v4_3t_core.zip
--2021-02-25 12:45:31--  https://sourceforge.net/projects/snpeff/files/snpEff_v4_3t_core.zip
Resolving dtn07-e0 (dtn07-e0)... 10.1.200.243
Connecting to dtn07-e0 (dtn07-e0)|10.1.200.243|:3128... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/projects/snpeff/files/snpEff_v4_3t_core.zip/ [following]
--2021-02-25 12:45:31--  https://sourceforge.net/projects/snpeff/files/snpEff_v4_3t_core.zip/
Connecting to dtn07-e0 (dtn07-e0)|10.1.200.243|:3128... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://sourceforge.net/projects/snpeff/files/snpEff_v4_3t_core.zip/download [following]
--2021-02-25 12:45:31--  https://sourceforge.net/projects/snpeff/files/snpEff_v4_3t_core.zip/download
Connecting to dtn07-e0 (dtn07-e0)|10.1.200.243|:3128... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/snpeff/snpEff_v4_3t_core.zip?r=&ts=1614275132&use_mirror=pilotfiber [following]
--2021-02-25 12:45:32--  https://downloads.sourceforge.net/project/snpeff/snpEff_v4_3t_core.zip?r=&ts=1614275132&use_mirror=pilotfiber
Connecting to dtn07-e0 (dtn07-e0)|10.1.200.243|:3128... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://pilotfiber.dl.sourceforge.net/project/snpeff/snpEff_v4_3t_core.zip [following]
--2021-02-25 12:45:32--  https://pilotfiber.dl.sourceforge.net/project/snpeff/snpEff_v4_3t_core.zip
Connecting to dtn07-e0 (dtn07-e0)|10.1.200.243|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 69708122 (66M) [application/octet-stream]
100%[===================================================================================================================================================>] 69,708,122  68.4KB/s   in 15m 39s
2021-02-25 13:01:11 (72.5 KB/s) - ‘snpEff_v4_3t_core.zip’ saved [69708122/69708122]
Saving to: ‘snpEff_v4_3t_core.zip’
```

Following unzipping, I show that the genome I am looking for is in the config: 

```
grep "grch38.86" snpEff.config -i
GRCh38.86.genome : Homo_sapiens
GRCh38.86.reference : ftp://ftp.ensembl.org/pub/release-86/gtf/
```
So I try to carry out the download, but run into this error:
```
java -jar snpEff.jar download GRCh38.86
00:00:00        ERROR while connecting to http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh38.86.zip
java.lang.RuntimeException: java.net.UnknownHostException: downloads.sourceforge.net
        at org.snpeff.util.Download.download(Download.java:178)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
        at org.snpeff.SnpEff.run(SnpEff.java:1183)
        at org.snpeff.SnpEff.main(SnpEff.java:162)
Caused by: java.net.UnknownHostException: downloads.sourceforge.net
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.snpeff.util.Download.download(Download.java:117)
```

Notably, if I take my browser to the address in the second line of the error the download starts immediately. So the address appears valid to me, but something from the command line download is leading to issues. Perhaps there is a preferred/alternative database.repository option to avoid this UnknownHost issue? Thank you for any help on this!

**Comment by pcingola** [comment]
Please upgrade to the latest SnpEff version (5.0).
We've migrated all the databases to Azure because of this issue.
