### ISSUE TITLE
Bug in building regulationary elements database

### ISSUE THREAD

**Issue by FarmOmics** [pcingola/SnpEff#304]
I followed the protocol in your website to prepare regulationary elements database:
I put bed file in ./regulation.bed directory, then I run 
snpEff build -c snpEff.config -v -onlyReg Sscrofa11.1

When it reads bed files, everything looks okay,
00:00:03        Reading file '/home/dguan/bin/snpEff/data/Sscrofa11.1/regulation.bed//regulation.Cerebellum.E13.bed'
00:00:03        Done
        Total lines                 : 61274
        Total annotation count      : 851063
        Percent                     : 101.0%
        Total annotated length      : 2566226663
        Number of cell/annotations  : 15
00:00:03        Creating consensus for cell type: Cerebellum
00:00:03        Sorting: Cerebellum     , size: 851063
00:00:03        Adding to final consensus
00:00:04        Final consensus for cell type: Cerebellum       , size: 842726

After that, it reports problem:

java.lang.RuntimeException: java.io.FileNotFoundException: null/regulation_Cerebellum.bin (No such file or directory)
        at org.snpeff.serializer.MarkerSerializer.save(MarkerSerializer.java:329)
        at org.snpeff.interval.Markers.save(Markers.java:393)
        at org.snpeff.RegulationFileConsensus.save(RegulationFileConsensus.java:164)
        at org.snpeff.RegulationConsensusMultipleBed.consensusByRegType(RegulationConsensusMultipleBed.java:69)
        at org.snpeff.RegulationConsensusMultipleBed.run(RegulationConsensusMultipleBed.java:139)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.readRegulationBed(SnpEffCmdBuild.java:286)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:390)
        at org.snpeff.SnpEff.run(SnpEff.java:1183)
        at org.snpeff.SnpEff.main(SnpEff.java:162)
Caused by: java.io.FileNotFoundException: null/regulation_Cerebellum.bin (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at org.snpeff.serializer.MarkerSerializer.save(MarkerSerializer.java:318)

**Comment by Just08** [comment]
Hi,
I've got the same issue .
A part of problem probably came from : https://github.com/pcingola/SnpEff/blob/2393f5ebc999157266d649858d40f509f4924f47/src/main/java/org/snpeff/snpEffect/Config.java#L342 
Have you find a way to fix it ?

**Comment by NikdAK** [comment]
I can confirm the bug regarding the regulatory database build. 
Anyways I found a workaround: Convert the BED to GFF
If the format is like this it will just work. Only columns 1,4,5,9 need valid entries. For the attributes only Cell_type seems to be mandatory, but setting name, alias, etc. could possibly be useful somewhen.

`chr1	source	feature	4426826	4427337	.	.	.	Cell_type=CHD2_CH12_LX__Enriched_Site`

All bed files should be combined into a single gff, which can be .gz to save space.
