### ISSUE TITLE
Database building issue enable to run SNPEFF

### ISSUE THREAD

**Issue by ankush290307** [pcingola/SnpEff#337]
ERROR while connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_pg.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:178)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1233)
	at org.snpeff.SnpEff.loadDb(SnpEff.java:520)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:922)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)
Caused by: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:127)
	... 9 more
java.lang.RuntimeException: Genome download failed!
	at org.snpeff.SnpEff.loadDb(SnpEff.java:521)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:922)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)

**Comment by pcingola** [comment]
Sorry, the information provided is not enough to reproduce the error or help you to fix it.
Please read the guidelines https://pcingola.github.io/SnpEff/help/
