### ISSUE TITLE
Error downloading cat's genome

### ISSUE THREAD

**Issue by gubrins** [pcingola/SnpEff#386]
**Describe the issue**
I can't upload the Cat genome from Ensembl.

**To Reproduce**
1. SnpEff version: SnpEff 5.1
2. Genome version: CAT.63, as shown here: http://pcingola.github.io/SnpEff/features/
3. SnpEff full command line: java -jar snpEff.jar download CAT.63
4. Output / Error message: Please include detailed infomration, such as transcript ID, VCF line output, etc.
```
java.lang.RuntimeException: Property: 'CAT.63.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:104)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:784)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:751)
	at org.snpeff.snpEffect.Config.init(Config.java:529)
	at org.snpeff.snpEffect.Config.<init>(Config.java:116)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:429)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:105)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:97)
	at org.snpeff.SnpEff.run(SnpEff.java:1141)
	at org.snpeff.SnpEff.main(SnpEff.java:160)
```

**Expected behavior**
To download the cat's genome.

**Data**
Not needed

**Additional context**
Not needed

**Comment by pcingola** [comment]
Currently built databases are on ENSEMBL version is 105 (version 63 is over 10 years old).
It's better to upgrade to the latest database versions.
