### ISSUE TITLE
Error downloading E. coli database

### ISSUE THREAD

**Issue by alexwong1357** [pcingola/SnpEff#464]
**Describe the issue**
I encounter an error message trying to download an E. coli database

**To Reproduce**
1. SnpEff version: 4.5
2. Genome version: k_12_substr_mg1655
3. SnpEff full command line: java -jar snpEff.jar download Escherichia_coli_str_k_12_substr_mg1655
4. Output / Error message: 
ERROR while connecting to http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_Escherichia_coli_str_k_12_substr_mg1655.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:178)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)
Caused by: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
	at org.snpeff.util.Download.download(Download.java:127)
	... 5 more

**Expected behavior**
Download of database

**Data**
Sample data. No need to add the full genomic dataset, but a few input lines enough to reproduce the conditions.
WARNING: Always attach the data files such as VCF lines.

**Additional context**

**Comment by pcingola** [comment]
Access issues have been solve long time ago
