### ISSUE TITLE
Cannot invoke "org.snpeff.interval.Marker.getChromosomeName()" because "marker" is null

### ISSUE THREAD

**Issue by jfass** [pcingola/SnpEff#469]
**Describe the bug**
When annotating a VCF merged from five variant callers, one line fails with the error msg below. The line is the final one of ~9 similar lines, with data from only the 4th variant caller (VarDict), and the alt "sequence" is "\<DUP\>".

**To Reproduce**
1. SnpEff version: 5.1d
2. Genome version: GRCh38.mane.1.0.ensembl
3. SnpEff full command line:  
(within a make recipe)
```
        docker run --rm $(dockerops) -v `pwd`:/tmp/data -w /tmp/data 3sp/snpeff \
          /bin/bash -c ' \
            cd tmp/nwes/annotate/ \
            && java -Xmx16G -jar /opt/conda/share/snpeff-*/snpEff.jar eff \
              -v \
              -datadir /tmp/data/ref/snpeff \
              -nodownload \
              -s /tmp/data/tmp/nwes/annotate/snpEff.summary \
              GRCh38.mane.1.0.ensembl \
              /tmp/data/tmp/nwes/annotate/merged.vcf \
              > /tmp/data/tmp/nwes/annotate/temp.snpeff.vcf'
```
4. Output / Error message: Please include a full VCF line output
```
[...]
00:00:30 Loading sequences for chromosome '19' from file '/tmp/data/ref/snpeff/GRCh38.mane.1.0.ensembl/sequence.19.bin'
00:00:30 Building sequence tree for chromosome '19'
00:00:30 Done. Loaded 1163 sequences.
java.lang.NullPointerException: Cannot invoke "org.snpeff.interval.Marker.getChromosomeName()" because "marker" is null                                                                   at org.snpeff.interval.Marker.includes(Marker.java:474)
        at org.snpeff.interval.MarkerSeq.getSequence(MarkerSeq.java:238)                                                                                                                  at org.snpeff.interval.MarkerSeq.applyDup(MarkerSeq.java:117)                                                                                                                     at org.snpeff.interval.MarkerSeq.apply(MarkerSeq.java:67)
        at org.snpeff.interval.Exon.apply(Exon.java:82)
        at org.snpeff.interval.Exon.apply(Exon.java:19)                                                                                                                                   at org.snpeff.interval.IntervalAndSubIntervals.apply(IntervalAndSubIntervals.java:97)
        at org.snpeff.interval.Transcript.apply(Transcript.java:293)                                                                                                                      at org.snpeff.interval.codonChange.CodonChangeStructural.codonsRefAlt(CodonChangeStructural.java:134)                                                                             at org.snpeff.interval.codonChange.CodonChangeDup.exonsCoding(CodonChangeDup.java:92)
        at org.snpeff.interval.codonChange.CodonChangeDup.exons(CodonChangeDup.java:82)                                                                                                   at org.snpeff.interval.codonChange.CodonChangeStructural.codonChange(CodonChangeStructural.java:82)
        at org.snpeff.interval.Exon.variantEffect(Exon.java:344)
        at org.snpeff.interval.Transcript.variantEffect(Transcript.java:1958)
        at org.snpeff.interval.Gene.variantEffect(Gene.java:595)
        at org.snpeff.snpEffect.SnpEffectPredictor.variantEffect(SnpEffectPredictor.java:714)
        at org.snpeff.snpEffect.SnpEffectPredictor.variantEffect(SnpEffectPredictor.java:692)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotateVariant(SnpEffCmdEff.java:387)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:202)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:474)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:139)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:918)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:875)
        at org.snpeff.SnpEff.run(SnpEff.java:1141)
        at org.snpeff.SnpEff.main(SnpEff.java:160)
ERROR: Error while processing VCF entry (line 49710) :
        chr19   47475477        .       C       <DUP>   29.0    PASS    SAMPLE=normal;TYPE=DUP;VD=2;BIAS=0:2;REFBIAS=0:0;VARBIAS=1:1;PMEAN=52;PSTD=1;QUAL=29.4;QSTD=1;SBF=1;ODDRAT
IO=0;MQ=60;SN=4;HIAF=1;ADJAF=1;SHIFT3=0;MSI=0;MSILEN=0;NM=0;HICNT=2;HICOV=2;LSEQ=CCTCCAACCCCTGTAGCCGA;RSEQ=TTTGAGACGGAGTCTTGCTC;DUPRATE=0;SVTYPE=DUP;SVLEN=9246;SPLITREAD=2;SPANPA
IR=0;DP=2;AF=1;AN=2;AC=2        GT:DP:VD:AD:AF:RD:ALD   ./.:.:.:.:.:.:. ./.:.:.:.:.:.:. ./.:.:.:.:.:.:. 1/1:2:2:0,2:1:0,0:1,1   ./.:.:.:.:.:.:.
java.lang.NullPointerException: Cannot invoke "org.snpeff.interval.Marker.getChromosomeName()" because "marker" is null
00:00:30 Loading sequences for chromosome '20' from file '/tmp/data/ref/snpeff/GRCh38.mane.1.0.ensembl/sequence.20.bin'
[...]
```
  
**Expected behavior**
A clearer error, if the gene or variant annotation is incorrect or unexpected in some way. Also, no output is written in the case of this error, but output for many other non-problematic lines could be output, presumedly.

**Data**
Sample data. No need to add the full genomic dataset, but a few input lines enough to reproduce the conditions.
WARNING: Always attach the data files such as VCF lines.
 Error can be reproduced with attached three line VCF file "merged.txt" ... extension changed from vcf for GH Issue attachment.
[merged.txt](https://github.com/pcingola/SnpEff/files/11153517/merged.txt)
 
**Additional context**

**Comment by jfass** [comment]
[merged.txt](https://github.com/pcingola/SnpEff/files/11153525/merged.txt)

**Comment by jfass** [comment]
Ah. GRCh38.mane.1.0.ensembl doesn't have "chr" in the chromosome names.
