### ISSUE TITLE
Build tests are failing in Eclipse

### ISSUE THREAD

**Issue by JohnZaharick** [pcingola/SnpEff#481]
**Describe the bug**
Commit [80e0678](https://github.com/pcingola/SnpEff/commit/80e06785027fb9d7bfb858cd9c385df30a627fd8) is failing tests when I attempt to build it in Eclipse.  I have been able to successfully build SnpEff as a Maven project prior to pulling the June 20, 2023 commits.

**To Reproduce**
1. SnpEff version: [80e0678](https://github.com/pcingola/SnpEff/commit/80e06785027fb9d7bfb858cd9c385df30a627fd8)
2. Genome version: N/A
3. SnpEff full command line: Maven build command from within Eclipse
4. Output / Error message: Please include a full VCF line output

```
Running org.snpeff.snpEffect.testCases.integration.TestCasesAnn
TestCasesAnn.test_01_VcfRawAlt(146):	Test
TestCasesAnn.test_01_Annotation_Stop(81):	Test
TestCasesAnn.test_02_Annotation_SpliceRegion(187):	Test
TestCasesAnn.test_05_Annotation_EndOfChromosome(373):	Test
TestCasesAnn.test_03_Annotation_NonSyn(249):	Test
TestCasesAnn.test_04_Annotation_Intergenic(311):	Test
Tests run: 6, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.297 sec <<< FAILURE!
org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_01_VcfRawAlt()  Time elapsed: 0.296 sec  <<< FAILURE!
java.lang.RuntimeException: Property: 'testHg3775Chr1.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:103)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:786)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:753)
	at org.snpeff.snpEffect.Config.init(Config.java:529)
	at org.snpeff.snpEffect.Config.<init>(Config.java:116)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:435)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:889)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_01_VcfRawAlt(TestCasesAnn.java:157)

org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_01_Annotation_Stop()  Time elapsed: 0 sec  <<< FAILURE!
java.lang.RuntimeException: Property: 'test_ENSG00000158062.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:103)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:786)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:753)
	at org.snpeff.snpEffect.Config.init(Config.java:529)
	at org.snpeff.snpEffect.Config.<init>(Config.java:116)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:435)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:889)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.annotate(TestCasesAnn.java:44)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.annotateFirst(TestCasesAnn.java:57)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_01_Annotation_Stop(TestCasesAnn.java:85)

org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_02_Annotation_SpliceRegion()  Time elapsed: 0 sec  <<< FAILURE!
java.lang.RuntimeException: Property: 'test_ENSG00000158062.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:103)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:786)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:753)
	at org.snpeff.snpEffect.Config.init(Config.java:529)
	at org.snpeff.snpEffect.Config.<init>(Config.java:116)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:435)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:889)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.annotate(TestCasesAnn.java:44)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.annotateFirst(TestCasesAnn.java:57)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_02_Annotation_SpliceRegion(TestCasesAnn.java:191)

org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_05_Annotation_EndOfChromosome()  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_05_Annotation_EndOfChromosome(TestCasesAnn.java:376)

org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_03_Annotation_NonSyn()  Time elapsed: 0 sec  <<< FAILURE!
java.lang.RuntimeException: Property: 'test_ENSG00000158062.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:103)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:786)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:753)
	at org.snpeff.snpEffect.Config.init(Config.java:529)
	at org.snpeff.snpEffect.Config.<init>(Config.java:116)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:435)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:889)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.annotate(TestCasesAnn.java:44)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.annotateFirst(TestCasesAnn.java:57)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_03_Annotation_NonSyn(TestCasesAnn.java:253)

org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_04_Annotation_Intergenic()  Time elapsed: 0 sec  <<< FAILURE!
java.lang.RuntimeException: Property: 'test_ENSG00000158062.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:103)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:786)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:753)
	at org.snpeff.snpEffect.Config.init(Config.java:529)
	at org.snpeff.snpEffect.Config.<init>(Config.java:116)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:435)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:889)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.annotate(TestCasesAnn.java:44)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.annotateFirst(TestCasesAnn.java:57)
	at org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_04_Annotation_Intergenic(TestCasesAnn.java:315)

org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.RuntimeException: Property: 'testCase.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:103)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:786)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:753)
	at org.snpeff.snpEffect.Config.init(Config.java:529)
	at org.snpeff.snpEffect.Config.<init>(Config.java:104)
	at org.snpeff.snpEffect.testCases.integration.TestCasesHgvsBase.initSnpEffPredictor(TestCasesHgvsBase.java:78)
	at org.snpeff.snpEffect.testCases.integration.TestCasesHgvsBase.init(TestCasesHgvsBase.java:66)
	at org.snpeff.snpEffect.testCases.integration.TestCasesHgvsBase.<init>(TestCasesHgvsBase.java:45)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.apache.maven.surefire.junit.PojoTestSet.<init>(PojoTestSet.java:63)
	at org.apache.maven.surefire.junit.JUnit3Provider.createTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:97)
	... 9 more

Results :

Failed tests:   org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_01_VcfRawAlt(): Property: 'testHg3775Chr1.genome' not found
  org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_01_Annotation_Stop(): Property: 'test_ENSG00000158062.genome' not found
  org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_02_Annotation_SpliceRegion(): Property: 'test_ENSG00000158062.genome' not found
  org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_05_Annotation_EndOfChromosome()
  org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_03_Annotation_NonSyn(): Property: 'test_ENSG00000158062.genome' not found
  org.snpeff.snpEffect.testCases.integration.TestCasesAnn.test_04_Annotation_Intergenic(): Property: 'test_ENSG00000158062.genome' not found

Tests run: 6, Failures: 6, Errors: 0, Skipped: 0
```

**Comment by pcingola** [comment]
Sorry, I dropped Eclipse long time ago, but this sounds like the `snpEff.config` used does not contain the test cases entries. Maybe copying the file from the config to SnpEff's project (workspace) directory helps to solve the issue.

Let me know if you want to contribute to the project, I'll be happy to help out.
