### ISSUE TITLE
i was working on Variant Annotation  ...the error  was genes.gff not found 

### ISSUE THREAD

**Issue by singha30** [pcingola/SnpEff#511]
Command executed:

  bcftools annotate --header-lines /Data/data/raja/cfdna/nextflow1/bin/syn3_header.txt LCR_FILTERED > FILTERED_hd.vcf
  **java -jar -Xmx4g /Data/data/raja/cfdna/nextflow1/bin/snpEff/snpEff.jar  eff -dataDir /Data/data/raja/cfdna/nextflow1/bin
/snpEff/data  -cancer -noLog -csvStats CSV_STATS -s HTML_REPORT /Data/data/raja/cfdna/nextflow1/bin/snpEff/Data/data/GRCh38.p14 FILTERED_hd.vcf > SNPEFF_ANNOTATED.vcf**
  java -jar /Data/data/raja/cfdna/nextflow1/bin/SNPEFF/SnpSift.jar annotate /Data/data/raja/cfdna/nextflow1/bin/snpEff/DBS
NP_DATABASE -tabix -noLog SNPEFF_ANNOTATED.vcf > DBSNP_ANNOTATED.vcf

Command exit status:
  255

Command output:
  (empty)

**### Command error:**
  java.lang.RuntimeException: Property: '/Data/data/raja/cfdna/nextflow1/bin/snpEff/Data/data/GRCh38.p14.genome' not found
        at org.snpeff.interval.Genome.<init>(Genome.java:103)
        at org.snpeff.snpEffect.Config.readConfig(Config.java:757)
        at org.snpeff.snpEffect.Config.init(Config.java:532)
        at org.snpeff.snpEffect.Config.<init>(Config.java:119)
        at org.snpeff.SnpEff.loadConfig(SnpEff.java:449)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:883)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:869)
        at org.snpeff.SnpEff.run(SnpEff.java:1173)
        at org.snpeff.SnpEff.main(SnpEff.java:163)

1. link  **Variant Annotation  using snpEff** :- https://github.com/hbctraining/variant_analysis/blob/main/lessons/11_variant_annotation.md
2.  code :- **# Run SnpEff
java -jar -Xmx4g $SNPEFF/snpEff.jar  eff \
-dataDir $DATADIR \
-cancer \
-noLog \
-csvStats $CSV_STATS \
-s $HTML_REPORT \
$REFERENCE_DATABASE \
$FILTERED_VCF_FILE_WITH_PEDIGREE_HEADER \
> $SNPEFF_ANNOTATED_VCF_FILE**

Let's breakdown this command and discuss each argument:

- java -jar $SNPEFF/snpEff.jar  eff Snpeff This calls the eff package within SnpEff to annotate variants.
- 
- -dataDir $DATADIR This is the path to the data directory that holds the SnpEff annotations
- 
- -cancer Performs cancer-mode
- 
- -noLog This does not report command usage to SnpEff's server
- 
- -csvStats $CSV_STATS This produces a flat-text file with summary statistics regarding the variants annotated. (Optional)
- 
- -s $HTML_REPORT This creates an HTML file with summary statistics regarding the variants annotated. This HTML file is mostly just an HTML stylized version of the CSV file above. (Optional)
- 
- $REFERENCE_DATABASE This is the SnpEff database we are going to use for the annotation.
- 
- $FILTERED_VCF_FILE_WITH_PEDIGREE_HEADER This is the input VCF file to be annotated
- 
- > $SNPEFF_ANNOTATED_VCF_FILE The output of SnpEff will be redirected into this VCF file.

**Comment by singha30** [comment]
1.This is the code which i was trying to run :- ****java -jar -Xmx4g /Data/data/raja/cfdna/nextflow1/bin/snpEff/snpEff.jar eff -dataDir /Data/data/raja/cfdna/nextflow1/bin/snpEff/data -cancer -noLog -csvStats CSV_STATS -s HTML_REPORT /Data/data/raja/cfdna/nextflow1/bin/snpEff/Data/data/GRCh38.p14   FILTERED_hd.vcf > SNPEFF_ANNOTATED.vcf**
2. I was working on the Gatk Variant Annotation 
3. i have followed the step of snpEff

**Comment by PriyaV229** [comment]
hello @singha30  I think you have missed out some step so this error is showing up 
1. you had loaded the SnpEff module
2. download **REFERENCE DATABASE**  as given in the doc 
3. Setting up Cancer-mode using the txt file and sbatch
# Using SnpEff to annotate our variants
# Load modules
# Assign variables
etc.......
then Submit this script using: **sbatch variant_annotation_normal_tumor.sbatch**
Tip: Next time maybe you can attach log files instead of copy pasting the content.

**Comment by pcingola** [comment]
Thank you for taking the time to report this issue. After reviewing our backlog, we've decided to close older issues that we realistically won't be able to address. If this is still relevant, please feel free to reopen it or file a new issue and we'll be happy to take another look.
