### ISSUE TITLE
Problems with building database: WARNING_EXON_NOT_FOUND

### ISSUE THREAD

**Issue by sarahveronica** [pcingola/SnpEff#518]
Hello, I tried to build databases for 6 Brassica species using the latest build (5.2 (2023-09-29)). For 5 of them, this worked out nicely and we were able to annotate our SNPs. However, using the following code

java -jar snpEff.jar build -gff3 -v Brassica_rapa_Chiifu_v3_5

for Brassica rapa Chiifu v3.5 (http://brassicadb.cn/#/Download/), I constantly get the following error message:

WARNING_EXON_NOT_FOUND: WARNING: Cannot find first exonic position after 3933875 for transcript 'BraA01g008110.3.5C.2'
java.lang.RuntimeException: Fatal Error: First exon needs correction: This should never happen!
	This method is supposed to be called AFTER method
	SnpEffPredictorFactory.frameCorrectionFirstCodingExon(), which
	should have taken care of this problem.
	A01:3932655-3933874, strand: -, id:BraA01g008110.3.5C.2, bioType:protein_coding, Protein
		5'UTR   :	A01	3932655-3932739 UTR_5_PRIME 'BraA01g008110.3.5C.2.utr5p1'
		5'UTR   :	A01	3933071-3933087 UTR_5_PRIME 'BraA01g008110.3.5C.2.utr5p2'
		Exons:
		A01:3932655-3932739 'BraA01g008110.3.5C.2.utr5p1', rank: 3, frame: ., sequence: cgtggaatagagatgcggcaccggtgaggaagatgagtttgattgggagattcgagccactaatatcgtgacttctctaaacgac
		A01:3933071-3933269 'BraA01g008110.3.5C.2.exon2', rank: 2, frame: 0, sequence: ctagcaagacgggtgtagagaagctgcttagacaactcttggcacttctccacagtggcaggctcctggatgtaatgcttgttcttctcaagcaactgcctgtaataggaagtcccatgcttagccacaaactttgaagcctcacacgcctttgactgaacttgtaccaacttcgatgccatcttcaaaaaaccaaatc
		A01:3933510-3933874 'BraA01g008110.3.5C.2.exon3', rank: 1, frame: ., sequence: aatagaaacttcctctggaattttttgttctttattaatctcaaacttatcaaagagagttttagcaaaatggaaattttctcagatccaaatactctgtttccgtttcagggaaaaacttgtaaaaaaaaaattgattcagattacacaatcttgttcaagttattgttcctctctttcaagggtaatagccggtgaaggtgaatcctcttccggcgatttctcctgcgcagtaccacgcaaagcattcgagaccaaacaatgcagcaattcctgcatcttctaccttcagatcgcttctgttcttccacaagttctttgcgtagtctacttccttccagaaagtctcatagcgtttgggaatg
		3'UTR   :	A01	3933697-3933874 UTR_3_PRIME 'BraA01g008110.3.5C.2.utr3p1'
		CDS     :	ccgtttcagggaaaaacttgtaaaaaaaaaattgattcagattacacaatcttgttcaagttattgttcctctctttcaagggtaatagccggtgaaggtgaatcctcttccggcgatttctcctgcgcagtaccacgcaaagcattcgagaccaaacaatgcagcaattcctgcatcttctaccttcagatcgcttctgttcttccacaagttctttgcgtagtctacttccttccagaaagtctcatagcgtttgggaatgctagcaagacgggtgtagagaagctgcttagacaactcttggcacttctccacagtggcaggctcctggatgtaatgcttgttcttctcaagcaactgcctgtaat
		Protein :	PFQGKTCKKKIDSDYTILFKLLFLSFKGNSR*R*ILFRRFLLRSTTQSIRDQTMQQFLHLLPSDRFCSSTSSLRSLLPSRKSHSVWEC*QDGCREAA*TTLGTSPQWQAPGCNACSSQATACN

	at org.snpeff.interval.Transcript.frameCorrectionNonFirstCodingExon(Transcript.java:1021)
	at org.snpeff.interval.Transcript.frameCorrection(Transcript.java:900)
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactory.frameCorrection(SnpEffPredictorFactory.java:605)
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactory.finishUp(SnpEffPredictorFactory.java:576)
	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:357)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:414)
	at org.snpeff.SnpEff.run(SnpEff.java:1173)
	at org.snpeff.SnpEff.main(SnpEff.java:163)
java.lang.RuntimeException: Error reading file '/homes/sschiess/programs/snpEff/data/Brassica_rapa_Chiifu_v3_5/genes.gff'
java.lang.RuntimeException: Fatal Error: First exon needs correction: This should never happen!
	This method is supposed to be called AFTER method
	SnpEffPredictorFactory.frameCorrectionFirstCodingExon(), which
	should have taken care of this problem.
	A01:3932655-3933874, strand: -, id:BraA01g008110.3.5C.2, bioType:protein_coding, Protein
		5'UTR   :	A01	3932655-3932739 UTR_5_PRIME 'BraA01g008110.3.5C.2.utr5p1'
		5'UTR   :	A01	3933071-3933087 UTR_5_PRIME 'BraA01g008110.3.5C.2.utr5p2'
		Exons:
		A01:3932655-3932739 'BraA01g008110.3.5C.2.utr5p1', rank: 3, frame: ., sequence: cgtggaatagagatgcggcaccggtgaggaagatgagtttgattgggagattcgagccactaatatcgtgacttctctaaacgac
		A01:3933071-3933269 'BraA01g008110.3.5C.2.exon2', rank: 2, frame: 0, sequence: ctagcaagacgggtgtagagaagctgcttagacaactcttggcacttctccacagtggcaggctcctggatgtaatgcttgttcttctcaagcaactgcctgtaataggaagtcccatgcttagccacaaactttgaagcctcacacgcctttgactgaacttgtaccaacttcgatgccatcttcaaaaaaccaaatc
		A01:3933510-3933874 'BraA01g008110.3.5C.2.exon3', rank: 1, frame: ., sequence: aatagaaacttcctctggaattttttgttctttattaatctcaaacttatcaaagagagttttagcaaaatggaaattttctcagatccaaatactctgtttccgtttcagggaaaaacttgtaaaaaaaaaattgattcagattacacaatcttgttcaagttattgttcctctctttcaagggtaatagccggtgaaggtgaatcctcttccggcgatttctcctgcgcagtaccacgcaaagcattcgagaccaaacaatgcagcaattcctgcatcttctaccttcagatcgcttctgttcttccacaagttctttgcgtagtctacttccttccagaaagtctcatagcgtttgggaatg
		3'UTR   :	A01	3933697-3933874 UTR_3_PRIME 'BraA01g008110.3.5C.2.utr3p1'
		CDS     :	ccgtttcagggaaaaacttgtaaaaaaaaaattgattcagattacacaatcttgttcaagttattgttcctctctttcaagggtaatagccggtgaaggtgaatcctcttccggcgatttctcctgcgcagtaccacgcaaagcattcgagaccaaacaatgcagcaattcctgcatcttctaccttcagatcgcttctgttcttccacaagttctttgcgtagtctacttccttccagaaagtctcatagcgtttgggaatgctagcaagacgggtgtagagaagctgcttagacaactcttggcacttctccacagtggcaggctcctggatgtaatgcttgttcttctcaagcaactgcctgtaat
		Protein :	PFQGKTCKKKIDSDYTILFKLLFLSFKGNSR*R*ILFRRFLLRSTTQSIRDQTMQQFLHLLPSDRFCSSTSSLRSLLPSRKSHSVWEC*QDGCREAA*TTLGTSPQWQAPGCNACSSQATACN

	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:362)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:414)
	at org.snpeff.SnpEff.run(SnpEff.java:1173)
	at org.snpeff.SnpEff.main(SnpEff.java:163)
00:00:27 Logging
00:00:32 Checking for updates...
00:00:35 Done.

The respective entry in the gff looks like this:
A01	IGV	mRNA	3932656	3933875	.	-	.	ID=BraA01g008110.3.5C.2;Parent=BraA01g008110.3.5C
A01	IGV	five_prime_UTR	3932656	3932740	.	-	.	ID=BraA01g008110.3.5C.2.utr5p1;Parent=BraA01g008110.3.5C.2
A01	IGV	five_prime_UTR	3933072	3933088	.	-	.	ID=BraA01g008110.3.5C.2.utr5p2;Parent=BraA01g008110.3.5C.2
A01	IGV	exon	3932656	3932740	.	-	.	ID=BraA01g008110.3.5C.2.exon1;Parent=BraA01g008110.3.5C.2
A01	IGV	exon	3933072	3933270	.	-	.	ID=BraA01g008110.3.5C.2.exon2;Parent=BraA01g008110.3.5C.2
A01	IGV	CDS	3933089	3933270	.	-	0	ID=cds.BraA01g008110.3.5C.2;Parent=BraA01g008110.3.5C.2
A01	IGV	exon	3933511	3933875	.	-	.	ID=BraA01g008110.3.5C.2.exon3;Parent=BraA01g008110.3.5C.2
A01	IGV	CDS	3933511	3933697	.	-	1	ID=cds.BraA01g008110.3.5C.2;Parent=BraA01g008110.3.5C.2
A01	IGV	three_prime_UTR	3933698	3933875	.	-	.	ID=BraA01g008110.3.5C.2.utr3p1;Parent=BraA01g008110.3.5C.2

I tried to delete the entry and run again, but it just finds the same for another entry. 
Running it with -noCheckCds and -noCheckProtein did not help.
How can I overcome this? A change in genome version would be extremely painful at this stage.

**Comment by pcingola** [comment]
Thank you for taking the time to report this issue. After reviewing our backlog, we've decided to close older issues that we realistically won't be able to address. If this is still relevant, please feel free to reopen it or file a new issue and we'll be happy to take another look.

**Comment by AlexTate** [comment]
@pcingola I believe this is the result of three_prime_UTR and five_prime_UTR feature types being swapped on the minus strand. In this case the "left" UTR should be labeled three_prime and the "right" UTR should be labeled five_prime ([sanity check](https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/add_utrs_to_gff/add_utrs_to_gff.py)). I encountered this same issue with a GFF for an assembly submitted to GenBank last year but I don't have the details on their annotation methods.

Validation with `table2asn` doesn't directly check for the discrepancy, though [ValidateCDSUTR](https://github.com/ncbi/ncbi-cxx-toolkit-public/blob/c5f0aaea51292d3c61e799887d03ef2d7d7a7976/src/objtools/validator/validerror_bioseq.cpp#L10716) catches some of the cases and [this comment](https://github.com/ncbi/ncbi-cxx-toolkit-public/blob/c5f0aaea51292d3c61e799887d03ef2d7d7a7976/src/objtools/validator/validerror_bioseq.cpp#L7681) seems to be on the right track but the code doesn't back it up in the way we would hope. The online GFF3 validator from genometools.org also doesn't flag it either. So it seems this format may be acceptable after all, but I can't find any justification for the leniency.
