### ISSUE TITLE
Database request: raccoon (Procyon lotor)

### ISSUE THREAD

**Issue by Joannakolodz** [pcingola/SnpEff#522]
### Database requests

1. Organism name: raccoon (Procyon lotor)
2. Link gene definition file (e.g. GTF / GFF / GenBank):
3. Link to Genome FASTA file/s: https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_028646535.1/
4. Link to CDS FASTA file:
5. Link to Protein FASTA file:

Note: Genome FASTA file might not be needed in some cases (e.g. GenBank files usually have genome sequence information)

Note: Either CDS or Protein FASTA files should be used to ensure correctness (sometimes these sequences are provided in the GenBank files).

### Feature requests

**Is your feature request related to a problem? Please describe.**

I tried to build a database by myself but I wasn't able to generate  GTF files nor genes.gff. 
While trying to build a database from GenBank files that was en error:
(ncbi_datasets) abacus@abacus:~/Downloads/snpEff$ ./scripts/buildDbNcbi.sh GCA_028646535.1
Downloading genome GCA_028646535.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    146      0 --:--:--  0:00:01 --:--:--   146
00:00:00 SnpEff version SnpEff 5.2a (build 2023-10-24 14:24), by Pablo Cingolani
00:00:00 Command: 'build'
00:00:00 Building database for 'GCA_028646535.1'
00:00:00 Reading configuration file 'snpEff.config'. Genome: 'GCA_028646535.1'
00:00:00 Reading config file: /home/abacus/Downloads/snpEff/snpEff.config
00:00:01 done
00:00:01 No sequence found in feature file.
00:00:01     Trying fasta file '/home/abacus/Downloads/snpEff/./data/genomes/GCA_028646535.1.fa'
00:00:01     Trying fasta file '/home/abacus/Downloads/snpEff/./data/GCA_028646535.1/sequences.fa'
java.lang.RuntimeException: Cannot find sequence for 'GCA_028646535.1'
    at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryFeatures.sequence(SnpEffPredictorFactoryFeatures.java:533)
    at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryFeatures.addFeatures(SnpEffPredictorFactoryFeatures.java:95)
    at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryFeatures.create(SnpEffPredictorFactoryFeatures.java:351)
    at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:414)
    at org.snpeff.SnpEff.run(SnpEff.java:1173)
    at org.snpeff.SnpEff.main(SnpEff.java:163)
java.lang.RuntimeException: Error reading file '/home/abacus/Downloads/snpEff/./data/GCA_028646535.1/genes.gbk'
java.lang.RuntimeException: Cannot find sequence for 'GCA_028646535.1'
    at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryFeatures.create(SnpEffPredictorFactoryFeatures.java:365)
    at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:414)
    at org.snpeff.SnpEff.run(SnpEff.java:1173)
    at org.snpeff.SnpEff.main(SnpEff.java:163)
00:00:01 Logging
00:00:02 Checking for updates...
00:00:04 Done.

**Comment by pcingola** [comment]
Thank you for taking the time to report this issue. After reviewing our backlog, we've decided to close older issues that we realistically won't be able to address. If this is still relevant, please feel free to reopen it or file a new issue and we'll be happy to take another look.
