### ISSUE TITLE
Problem  with downlading genome

### ISSUE THREAD

**Issue by javierAPC** [pcingola/SnpEff#526]
**Describe the issue**
Hi, I'm trying to annotate some VCF files, but when I attempt to run the annotation process, I encounter three errors: two related to "too many symbolic links" and one related to "not finding the genome". I tried running one of the test exposed in the web using different versions (GRCh38.105 and GRCh37.75), but I encountered the same error. Additionally, when I try to use `java -jar snpEff.jar download`, it gives the first two errors.

**To Reproduce**
1. SnpEff version: 5.2
2. Genome version: Any
3. SnpEff full command line:  java -Xmx8g -jar snpEff.jar GRCh37.75 examples/test.chr22.vcf > test.chr22.ann.vcf
4. Output / Error message: 
`java.lang.RuntimeException: java.io.IOException:  Too many levels of symbolic links
	at org.snpeff.util.Download.unzip(Download.java:374)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:41)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:61)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:110)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:97)
	at org.snpeff.SnpEff.run(SnpEff.java:1212)
	at org.snpeff.SnpEff.loadDb(SnpEff.java:514)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:884)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:869)
	at org.snpeff.SnpEff.run(SnpEff.java:1173)
	at org.snpeff.SnpEff.main(SnpEff.java:163)
Caused by: java.io.IOException:  Too many levels of symbolic links
	at java.base/java.io.UnixFileSystem.canonicalize0(Native Method)
	at java.base/java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:175)
	at java.base/java.io.File.getCanonicalPath(File.java:626)
	at org.snpeff.util.Download.unzip(Download.java:342)
	... 10 more
java.lang.RuntimeException: Genome download failed!
	at org.snpeff.SnpEff.loadDb(SnpEff.java:515)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:884)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:869)
	at org.snpeff.SnpEff.run(SnpEff.java:1173)
	at org.snpeff.SnpEff.main(SnpEff.java:163)
`
**Expected behavior**
My expectation was to receive a annotated VCF file, but instead I received a blank VCF file.
**Data**
One of example of my data
the file test.chr33.vcf from the examples directory

Update: i solve it, the data directory was an symbolic link instead of an actual dir. so i just delate it and now everything works

**Comment by javierAPC** [comment]
Update: i solve it, the data directory was an symbolic link instead of an actual dir. so i just delate it and now everything works
