### ISSUE TITLE
Error: Unknown option '-noCheckCds'

### ISSUE THREAD

**Issue by tania-k** [pcingola/SnpEff#528]
**Describe the issue**
Hello folks, 
Thank you for creating an important tool to help breakdown VCF results. 
I have an issue that has popped up and I am unsure how to progress as it doesn't seem to be an issue that genuinely makes sense.

I have snpeff/4.3t loaded into my university cluster as a module along with a separate conda environment with snpeff/4.3t but I am receiving the same issue.
It is an error involving the build option, `-noCheckCds` and `-noCheckProtein` where these options don't seem to exist? I've tried different versions of snpeff and I am receiving the same error. I am not sure what I am missing? I am running snpeff build on a custom more up-to-date genome of Histoplasma capsulatum.

Here is the script I ran:
`java -Xmx64g -jar /nas/longleaf/apps/snpeff/4.3q/snpEff/snpEff.jar build -datadir snpeff/data -c /nas/longleaf/home/taniak/taniak/Histo_PopGenomics/snpeff/snpEff.config -gff3 -noCheckCds -noCheckProtein -nodownload -v Histoplasma_capsulatum_WU24`

Here is the error log I am receiving.

> GFF is Histoplasma_capsulatum_WU24.gff3
>genome/FungiDB-67_HcapsulatumWU24_Genome.fasta
>00:00:00	SnpEff version SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani
>00:00:00	Command: 'build'
>Error: Unknown option '-noCheckCds'
>
>snpEff version SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani
>Usage: snpEff build [options] genome_version
>
>Build DB options:
>Database format option (default: Auto detect):
>	-embl                        : Use Embl format.
>	-genbank                     : Use GenBank format.
>	-gff2                        : Use GFF2 format (obsolete).
>	-gff3                        : Use GFF3 format.
>	-gtf22                       : Use GTF 2.2 format.
>	-knowngenes                  : Use KnownGenes table from UCSC.
>	-refseq                      : Use RefSeq table from UCSC.
>
>Database build options:
>	-cellType <type>             : Only build regulation tracks for cellType <type>.
>	-noStoreSeqs                 : Do not store sequence in binary files. Default: true
>	-onlyReg                     : Only build regulation tracks.
>	-regSortedByType             : The 'regulation.gff' file is sorted by 'regulation type' instead of sorted by chromosome:pos. >Default: false
>	-storeSeqs                   : Store sequence in binary files. Default: false
>
>Generic options:
>	-c , -config                 : Specify config file
>	-configOption name=value     : Override a config file option
>	-d , -debug                  : Debug mode (very verbose).
>	-dataDir <path>              : Override data_dir parameter from config file.
>	-download                    : Download a SnpEff database, if not available locally. Default: false
>	-nodownload                  : Do not download a SnpEff database, if not available locally.
>	-h , -help                   : Show this help and exit
>	-noLog                       : Do not report usage statistics to server
>	-t                           : Use multiple threads (implies '-noStats'). Default 'off'
>	-q , -quiet                  : Quiet mode (do not show any messages or errors)
>	-v , -verbose                : Verbose mode
>	-version                     : Show version number and exit
>
> java -Xmx64g -jar /nas/longleaf/apps/snpeff/4.3t/snpEff/snpEff.jar eff -c >/nas/longleaf/home/taniak/taniak/Histo_PopGenomics/snpEff/snpEff.config -dataDir >/nas/longleaf/home/taniak/taniak/Histo_PopGenomics/snpEff/data -v Histoplasma_capsulatum_WU24 >WU24_v1.All.allvariants_combined_selected.vcf > WU24_v1.All.snpEff.vcf
>
>00:00:00	SnpEff version SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani
>00:00:00	Command: 'eff'
>00:00:00	Reading configuration file '/nas/longleaf/home/taniak/taniak/Histo_PopGenomics/snpEff/snpEff.config'. Genome: >'Histoplasma_capsulatum_WU24'
>00:00:00	Reading config file: /work/users/t/a/taniak/Histo_PopGenomics/snpEff/snpEff.config
>00:00:00	done
>00:00:00	Reading database for genome version 'Histoplasma_capsulatum_WU24' from file >'/nas/longleaf/home/taniak/taniak/Histo_PopGenomics/snpEff/data/Histoplasma_capsulatum_WU24/snpEffectPredictor.bin' (this >might take a while)
>java.lang.RuntimeException: 	ERROR: Cannot read file >'/nas/longleaf/home/taniak/taniak/Histo_PopGenomics/snpEff/data/Histoplasma_capsulatum_WU24/snpEffectPredictor.bin'.
>	You can try to download the database by running the following command:
>		java -jar snpEff.jar download Histoplasma_capsulatum_WU24
>
>	at org.snpeff.snpEffect.SnpEffectPredictor.load(SnpEffectPredictor.java:62)
>	at org.snpeff.snpEffect.Config.loadSnpEffectPredictor(Config.java:579)
>	at org.snpeff.SnpEff.loadDb(SnpEff.java:520)
>	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1001)
>	at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
>	at org.snpeff.SnpEff.run(SnpEff.java:1183)
>	at org.snpeff.SnpEff.main(SnpEff.java:162)
>00:00:00	Logging
>00:00:01	Checking for updates...
>00:00:02	Done.
>Failed to open WU24_v1.All.snpEff.vcf: unknown file type

Thank you for your time!
Tania Kurbessoian, Ph.D.

**Comment by pcingola** [comment]
Thank you for taking the time to report this issue. After reviewing our backlog, we've decided to close older issues that we realistically won't be able to address. If this is still relevant, please feel free to reopen it or file a new issue and we'll be happy to take another look.
