### ISSUE TITLE
java.lang.NullPointerException at ca.mcgill.mcb.pcingola.interval.Variant.realignLeft(Variant.java:407)

### ISSUE THREAD

**Issue by asimenos** [pcingola/SnpEff#78]
Hi, and thanks for making snpEff!

I am trying to annotate variants, using the following command:

    java -jar snpEff.jar ann -noStats -t GRCh37.75 input.vcf >out.vcf

This worked fine with snpEff v4.1d. However, after upgrading to snpEff v4.1e, some variants are no longer annotated, and an error is shown in the console for these entries. The error is the following:
```
Error: Error while processing VCF entry (line 14841) :
	8	30958353	rs3087419	CT	C	531.77	.	AC=2;AF=1.00;AN=2;DB;DP=18;FS=0.000;GQ_MEAN=54.00;MLEAC=2;MLEAF=1.00;MQ=60.00;MQ0=0;NCC=0;QD=29.54;SOR=1.863	GT:AD:DP:GQ:PL	1/1:0,18:18:54:560,54,0
java.lang.NullPointerException
	at ca.mcgill.mcb.pcingola.interval.Variant.realignLeft(Variant.java:407)
	at ca.mcgill.mcb.pcingola.interval.Gene.variantEffect(Gene.java:468)
	at ca.mcgill.mcb.pcingola.snpEffect.SnpEffectPredictor.variantEffect(SnpEffectPredictor.java:639)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:52)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:18)
	at ca.mcgill.mcb.pcingola.akka.Worker.calculate(Worker.java:56)
	at ca.mcgill.mcb.pcingola.akka.Worker.onReceive(Worker.java:67)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:154)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:153)
	at akka.actor.Actor$class.apply(Actor.scala:311)
	at akka.actor.UntypedActor.apply(UntypedActor.scala:93)
	at akka.actor.ActorCell.invoke(ActorCell.scala:619)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:196)
	at akka.dispatch.Mailbox.run(Mailbox.scala:178)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
```

The error goes away if the `-t` command-line switch is omitted. To summarize, v4.1e with `-t` exhibits the problem; v4.1e without `-t` is fine, and v4.1d is also fine.  So perhaps some multi-threading changes were introduced between v4.1d and v4.1e which may be causing this?

**Comment by pcingola** [comment]
Thank you for reporting this! 
I'll take a look at it asap.

**Comment by pcingola** [comment]
Fixed in version 4.1F (just released).

**Comment by asimenos** [comment]
Confirmed. Thanks for fixing this so quickly.

**Comment by summerela** [comment]
I'm still running into this error frequently with SnpEff version SnpEff 4.1l (build 2015-10-03).  

    Error: Error while processing VCF entry (line 9060090) :
	5	27478165	rs80057514	A	G	.	.	.
    java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$ValueIterator.next(HashMap.java:950)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
	at java.util.ArrayList.addAll(ArrayList.java:559)
	at     ca.mcgill.mcb.pcingola.interval.IntervalAndSubIntervals.sortedStrand(IntervalAndSubIntervals.java:256)
	at ca.mcgill.mcb.pcingola.interval.Transcript.cds(Transcript.java:493)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.getCdsLength(VariantEffect.java:329)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.set(VcfEffect.java:1043)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:145)
	at   ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:97)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
	at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:66)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:18)
	at ca.mcgill.mcb.pcingola.akka.Worker.calculate(Worker.java:51)
	at ca.mcgill.mcb.pcingola.akka.Worker.onReceive(Worker.java:62)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:154)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:153)
	at akka.actor.Actor$class.apply(Actor.scala:311)
	at akka.actor.UntypedActor.apply(UntypedActor.scala:93)
	at akka.actor.ActorCell.invoke(ActorCell.scala:619)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:196)
	at akka.dispatch.Mailbox.run(Mailbox.scala:178)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
    java.lang.NullPointerException
	at ca.mcgill.mcb.pcingola.interval.Transcript.cds(Transcript.java:503)
	at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.getCdsLength(VariantEffect.java:329)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.set(VcfEffect.java:1043)
	at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:145)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:97)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
	at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
	at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:66)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.eff.WorkerEff.calculate(WorkerEff.java:18)
	at ca.mcgill.mcb.pcingola.akka.Worker.calculate(Worker.java:51)
	at ca.mcgill.mcb.pcingola.akka.Worker.onReceive(Worker.java:62)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:154)
	at akka.actor.UntypedActor$$anonfun$receive$1.apply(UntypedActor.scala:153)
	at akka.actor.Actor$class.apply(Actor.scala:311)
	at akka.actor.UntypedActor.apply(UntypedActor.scala:93)
	at akka.actor.ActorCell.invoke(ActorCell.scala:619)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:196)
	at akka.dispatch.Mailbox.run(Mailbox.scala:178)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:505)
	at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
	at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
