### ISSUE TITLE
Add truncation / elongation / abalation effects (improve compatibility with VEP)

### ISSUE THREAD

**Issue by pcingola** [pcingola/SnpEff#95]
Add truncation / elongation / abalation effects to improve compatibility with VEP:

    regulatory_region_ablation          SV causes ablation of a regulatory region
    regulatory_region_amplification     SV results in an amplification of a regulatory region
    transcript_ablation                 SV causes an ablation/deletion of a transcript feature
    transcript_amplification            SV causes an amplification of a transcript feature
    TFBS_ablation                       SV results in a deletion of the TFBS
    TFBS_amplification                  SV results in an amplification of a region containing TFBS
    feature_elongation                  SV causes an extension of a genomic feature wrt reference
    feature_truncation                  SV causes a reduction of a genomic feature compared to reference

From a user:

...I'm getting the following error parsing a VEP (ANN) annotated file with snpSift:

Exception in thread "main" java.lang.RuntimeException: Cannot parse EffectType 'TFBS_ablation'
        at ca.mcgill.mcb.pcingola.snpEffect.EffectType.parse(EffectType.java:88)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.parseEffect(VcfEffect.java:866)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.parseAnn(VcfEffect.java:726)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.parse(VcfEffect.java:710)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:252)
        at ca.mcgill.mcb.pcingola.vcf.VcfEntry.parseEffects(VcfEntry.java:926)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.FieldEff.getFieldString(FieldEff.java:63)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.Field.eval(Field.java:69)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.ExpressionBinary.eval(ExpressionBinary.java:25)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.ExpressionBinary.eval(ExpressionBinary.java:26)
        at ca.mcgill.mcb.pcingola.snpSift.lang.expression.ExpressionBinary.eval(ExpressionBinary.java:25)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdFilter.evaluate(SnpSiftCmdFilter.java:140)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:298)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:268)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSift.run(SnpSift.java:360)
        at ca.mcgill.mcb.pcingola.snpSift.SnpSift.main(SnpSift.java:69)

**Comment by pcingola** [comment]
Fixed.
