### ISSUE TITLE
Hgvs transcript NullPointerException for structural variants

### ISSUE THREAD

**Issue by chapmanb** [pcingola/SnpEff#96]
Pablo;
We've been working to add support for annotating structural variants with snpEff (4.1k) and ran into NullPointerExceptions when calculating HgvsProtein transcripts:
```
java.lang.NullPointerException
        at ca.mcgill.mcb.pcingola.interval.Transcript.apply(Transcript.java:327)
        at ca.mcgill.mcb.pcingola.snpEffect.HgvsProtein.posFs(HgvsProtein.java:322)
        at ca.mcgill.mcb.pcingola.snpEffect.HgvsProtein.toString(HgvsProtein.java:473)
        at ca.mcgill.mcb.pcingola.snpEffect.VariantEffect.getHgvsProt(VariantEffect.java:540)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.set(VcfEffect.java:1028)
        at ca.mcgill.mcb.pcingola.vcf.VcfEffect.<init>(VcfEffect.java:145)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.addInfo(VcfOutputFormatter.java:97)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.toString(VcfOutputFormatter.java:285)
        at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.endSection(OutputFormatter.java:112)
        at ca.mcgill.mcb.pcingola.outputFormatter.VcfOutputFormatter.endSection(VcfOutputFormatter.java:229)
        at ca.mcgill.mcb.pcingola.outputFormatter.OutputFormatter.printSection(OutputFormatter.java:145)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:276)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotateVcf(SnpEffCmdEff.java:443)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.annotate(SnpEffCmdEff.java:139)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:969)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:921)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:905)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:128)
```
This seems general and I could reproduce with output from 4 different callers (CNVkit, Lumpy, WHAM and Manta) and both human build 37 and 38. Here are two example files with the problems (https://gist.github.com/chapmanb/de12e55bbdefd5ea5824) that you can reproduce with:
```
snpEff -Xms750m -Xmx6g -dataDir $datadir GRCh37.75 hgvs-error-37.vcf > hgvs-error-37-snpeff.vcf
snpEff -Xms750m -Xmx6g -dataDir $datadir GRCh38.78 hgvs-error-38.vcf > hgvs-error-38-snpeff.vcf
```
Right now it looks like you call this HGVS prep code by default, but It would be fine to not have HGVS output for structural variants (via `-noHgvs` or other options). Thanks so much for any help or suggestions.

**Comment by pcingola** [comment]
Can you send a sample input VCF file that produces this error and the command line you are using?

**Comment by pcingola** [comment]
Oops! Sorry, that comment about the command line & VCF file was not for you.

**Comment by pcingola** [comment]
I think it should work OK now (version 4.1 L).

**Comment by chapmanb** [comment]
Pablo -- brilliant, thanks for the super fast fix. 4.1 L works perfectly. Much appreciated.
